"""Tests for mattstack rules: stack-specific agent files and harness adapters."""

from __future__ import annotations

from pathlib import Path

import pytest
import typer

from mattstack.commands.rules import (
    HARNESS_ADAPTERS,
    collect_canonical,
    render_adapter,
    run_rules,
    sync_harness_rules,
)


def _backend(tmp_path: Path, files: dict[str, str]) -> Path:
    backend = tmp_path / "backend"
    backend.mkdir()
    for name, content in files.items():
        (backend / name).write_text(content, encoding="utf-8")
    return tmp_path


@pytest.mark.parametrize(
    ("files", "expected", "forbidden"),
    [
        (
            {"pyproject.toml": '[project]\ndependencies = ["fastapi"]\n'},
            "alembic",
            ("django-ninja", "manage.py"),
        ),
        (
            {"package.json": '{"dependencies": {"@nestjs/core": "11"}}'},
            "bun run db:migrate",
            ("django-ninja", "manage.py", "uv run"),
        ),
        (
            {"pyproject.toml": '[project]\ndependencies = ["django-matt"]\n'},
            "django-matt",
            ("django-ninja (",),
        ),
    ],
)
def test_agent_files_describe_the_actual_backend(
    tmp_path: Path, files: dict[str, str], expected: str, forbidden: tuple[str, ...]
) -> None:
    _backend(tmp_path, files)
    run_rules(tmp_path, gsd=True)
    for name in ("CLAUDE.md", ".cursorrules", ".planning/PROJECT.md"):
        text = (tmp_path / name).read_text(encoding="utf-8")
        for phrase in forbidden:
            assert phrase not in text, f"{name} mentions {phrase!r}"
    assert expected in (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")


def test_claude_md_points_at_existing_component_guidance(tmp_path: Path) -> None:
    _backend(
        tmp_path,
        {
            "pyproject.toml": '[project]\ndependencies = ["django-ninja"]\n',
            "AGENTS.md": "# Backend\n",
            "justfile": "gauntlet-quick:\n    uv run python scripts/gauntlet.py --quick\n",
        },
    )
    run_rules(tmp_path)
    claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "`backend/AGENTS.md`" in claude
    assert "`cd backend && just gauntlet-quick`" in claude
    # Guidance that is absent on disk is never named.
    assert "backend/.omp/rules" not in claude


def test_agent_files_name_the_lockfile_package_manager(tmp_path: Path) -> None:
    _backend(tmp_path, {"pyproject.toml": '[project]\ndependencies = ["django-ninja"]\n'})
    frontend = tmp_path / "frontend"
    frontend.mkdir()
    (frontend / "package.json").write_text('{"devDependencies": {"vite": "6"}}')
    (frontend / "pnpm-lock.yaml").write_text("")
    run_rules(tmp_path)
    claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "ALWAYS use `pnpm`" in claude
    assert "pnpm run test" in claude


def test_unknown_backend_refuses_to_write(tmp_path: Path) -> None:
    _backend(tmp_path, {"pyproject.toml": "[project]\nname = 'x'\n"})
    with pytest.raises(typer.Exit) as exc:
        run_rules(tmp_path)
    assert exc.value.exit_code == 1
    assert not (tmp_path / "CLAUDE.md").exists()


def test_dry_run_shows_status_tags(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    _backend(tmp_path, {"pyproject.toml": '[project]\ndependencies = ["django-ninja"]\n'})
    (tmp_path / "CLAUDE.md").write_text("mine\n", encoding="utf-8")
    run_rules(tmp_path, dry_run=True)
    out = capsys.readouterr().out
    assert "[overwrite] CLAUDE.md" in out
    assert "[create] .cursorrules" in out
    assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == "mine\n"


def test_collect_canonical_concatenates_sorted(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".context").mkdir()
    (tmp_path / ".omp" / "RULES.md").write_text("# Rules\n", encoding="utf-8")
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".context" / "CONTEXT.md").write_text("# Context\n", encoding="utf-8")

    canonical = collect_canonical(tmp_path)

    assert "AGENTS.md" in canonical
    assert "RULES.md" in canonical
    assert "CONTEXT.md" in canonical
    assert canonical.index("AGENTS.md") < canonical.index("RULES.md")
    assert canonical.index("RULES.md") < canonical.index("CONTEXT.md")


def test_collect_canonical_ignores_non_md(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "notes.txt").write_text("ignored\n", encoding="utf-8")

    assert collect_canonical(tmp_path) == ""


def test_render_adapter_adds_header() -> None:
    out = render_adapter("body")

    assert "Generated by `mattstack rules sync`" in out
    assert "body" in out


def test_sync_writes_all_adapters(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path)

    assert len(written) == len(HARNESS_ADAPTERS)
    for rel in HARNESS_ADAPTERS.values():
        target = tmp_path / rel
        assert target.exists()
        assert "# Agents" in target.read_text(encoding="utf-8")


def test_sync_skips_existing_without_force(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".claude").mkdir(parents=True)
    (tmp_path / ".claude" / "CLAUDE.md").write_text("hand-edited\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path)

    assert (tmp_path / ".claude" / "CLAUDE.md").read_text(encoding="utf-8") == "hand-edited\n"
    assert len(written) == len(HARNESS_ADAPTERS) - 1


def test_sync_force_overwrites(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".claude").mkdir(parents=True)
    (tmp_path / ".claude" / "CLAUDE.md").write_text("hand-edited\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path, force=True)

    assert "# Agents" in (tmp_path / ".claude" / "CLAUDE.md").read_text(encoding="utf-8")
    assert len(written) == len(HARNESS_ADAPTERS)


def test_sync_never_duplicates_root_claude_md(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / "CLAUDE.md").write_text("generated by init\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path, force=True)

    # Claude Code reads both paths as the same project memory.
    assert not (tmp_path / ".claude" / "CLAUDE.md").exists()
    assert len(written) == len(HARNESS_ADAPTERS) - 1


def test_sync_errors_without_canonical(tmp_path: Path) -> None:
    with pytest.raises(typer.Exit) as exc:
        sync_harness_rules(tmp_path)

    assert exc.value.exit_code == 1
