"""Doctor checks for the local gate hook and declared MCP servers."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from mattstack.commands.doctor import _mcp_checks, _pre_push_check

PRE_PUSH_CONFIG = """\
repos:
  - repo: local
    hooks:
      - id: gauntlet
        name: gauntlet
        entry: just gauntlet-quick
        language: system
        stages: [pre-push]
"""


@pytest.mark.skipif(shutil.which("git") is None, reason="needs git")
def test_pre_push_hook_fails_until_installed(tmp_path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / ".pre-commit-config.yaml").write_text(PRE_PUSH_CONFIG, encoding="utf-8")

    missing = _pre_push_check(tmp_path)
    assert missing is not None and missing.status == "fail"

    hook = tmp_path / ".git" / "hooks" / "pre-push"
    hook.write_text("#!/bin/sh\n# File generated by pre-commit\n", encoding="utf-8")
    installed = _pre_push_check(tmp_path)
    assert installed is not None and installed.status == "ok"


def test_mcp_servers_fail_when_command_missing_or_url_unreachable(tmp_path: Path) -> None:
    servers = {
        "found": {"command": "git"},
        "missing": {"command": "mattstack-no-such-mcp-server"},
        "down": {"type": "http", "url": "http://127.0.0.1:1/mcp"},
        "bad": {"type": "http", "url": "ftp://example.com"},
    }
    (tmp_path / ".mcp.json").write_text(json.dumps({"mcpServers": servers}), encoding="utf-8")

    statuses = {c.check: c.status for c in _mcp_checks(tmp_path)}

    assert statuses == {
        "MCP server bad": "fail",
        "MCP server down": "fail",
        "MCP server found": "ok" if shutil.which("git") else "fail",
        "MCP server missing": "fail",
    }
