"""Post-processor to configure frontend for monorepo integration."""

from __future__ import annotations

from mattstack.config import FrontendFramework, ProjectConfig
from mattstack.utils.console import print_info


def setup_frontend_monorepo(config: ProjectConfig) -> None:
    """Configure frontend .env and proxy config for monorepo integration."""
    if not config.has_frontend or not config.has_backend:
        return

    if config.is_nextjs:
        _setup_nextjs_monorepo(config)
    elif config.frontend_framework in (
        FrontendFramework.REACT_RSBUILD,
        FrontendFramework.REACT_RSBUILD_KIBO,
    ):
        _setup_rsbuild_monorepo(config)
    else:
        _setup_vite_monorepo(config)


def _api_base_url(config: ProjectConfig) -> str:
    return f"http://localhost:{config.backend_api_port}/api/v1"


def _backend_origin(config: ProjectConfig) -> str:
    return f"http://localhost:{config.backend_api_port}"


def _setup_vite_monorepo(config: ProjectConfig) -> None:
    api_url = _api_base_url(config)
    if config.is_nestjs_backend:
        env_content = f"""\
VITE_API_BASE_URL={api_url}
VITE_AUTH_TOKEN_KEY=access_token
VITE_REFRESH_TOKEN_KEY=refresh_token
VITE_ENABLE_MOCK_API=false
"""
    else:
        env_content = f"""\
VITE_MODE=django-spa
VITE_API_BASE_URL={api_url}
VITE_AUTH_TOKEN_KEY=access_token
VITE_REFRESH_TOKEN_KEY=refresh_token
VITE_ENABLE_MOCK_API=false
VITE_DJANGO_CSRF_TOKEN_NAME=csrftoken
VITE_DJANGO_STATIC_URL=/static/
VITE_DJANGO_MEDIA_URL=/media/
VITE_DJANGO_API_PREFIX=/api/v1
"""

    (config.frontend_dir / ".env").write_text(env_content)
    (config.frontend_dir / ".env.monorepo").write_text(env_content)
    print_info("Configured frontend for monorepo mode")
    _create_vite_monorepo_config(config)
    _seed_generated_types(config)


def _seed_generated_types(config: ProjectConfig) -> None:
    """Seed `src/types/generated.ts` so the first sync has a target.

    Do not add the file to `src/types/index.ts`. The barrel already exports
    names such as ValidationErrorResponse from ./api, and a wildcard export
    of the generated file collides with them, which fails the type-check.
    Import the generated file directly until the names are reconciled.
    """
    types_dir = config.frontend_dir / "src" / "types"
    if not types_dir.is_dir():
        return

    generated = types_dir / "generated.ts"
    if not generated.exists():
        generated.write_text(
            "// Auto-generated by mattstack sync types — do not edit\n"
            "// Run `make sync-types` to populate this file.\n"
        )
        print_info("Seeded src/types/generated.ts for `mattstack sync types`")


def _setup_nextjs_monorepo(config: ProjectConfig) -> None:
    api_url = _api_base_url(config)
    env_content = f"""\
NEXT_PUBLIC_API_BASE_URL={api_url}
NEXT_PUBLIC_AUTH_TOKEN_KEY=access_token
NEXT_PUBLIC_REFRESH_TOKEN_KEY=refresh_token
"""
    (config.frontend_dir / ".env.local").write_text(env_content)
    print_info("Configured Next.js frontend for monorepo mode")
    _create_nextjs_monorepo_config(config)


def _create_vite_monorepo_config(config: ProjectConfig) -> None:
    origin = _backend_origin(config)
    proxy_entries = f"""\
      "/api": {{
        target: "{origin}",
        changeOrigin: true,
      }},"""

    if config.is_django_backend:
        proxy_entries += f"""
      "/static": {{
        target: "{origin}",
        changeOrigin: true,
      }},
      "/media": {{
        target: "{origin}",
        changeOrigin: true,
      }},
      "/admin": {{
        target: "{origin}",
        changeOrigin: true,
      }},"""

    content = f"""\
import {{ defineConfig }} from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({{
  plugins: [react()],
  resolve: {{
    alias: {{
      "@": path.resolve(__dirname, "./src"),
    }},
  }},
  server: {{
    port: 3000,
    proxy: {{
{proxy_entries}
    }},
  }},
  build: {{
    outDir: "dist",
    rollupOptions: {{
      output: {{
        assetFileNames: "static/css/[name]-[hash][extname]",
        chunkFileNames: "static/js/[name]-[hash].js",
        entryFileNames: "static/js/[name]-[hash].js",
      }},
    }},
  }},
}});
"""
    (config.frontend_dir / "vite.config.monorepo.ts").write_text(content)
    print_info("Created vite.config.monorepo.ts with API proxy")


def _create_nextjs_monorepo_config(config: ProjectConfig) -> None:
    origin = _backend_origin(config)
    rewrites = f"""\
      {{
        source: "/api/v1/:path*",
        destination: "{origin}/api/v1/:path*",
      }},"""

    if config.is_django_backend:
        rewrites += f"""
      {{
        source: "/admin/:path*",
        destination: "{origin}/admin/:path*",
      }},
      {{
        source: "/static/:path*",
        destination: "{origin}/static/:path*",
      }},"""

    content = f"""\
import type {{ NextConfig }} from "next";

const nextConfig: NextConfig = {{
  async rewrites() {{
    return [
{rewrites}
    ];
  }},
}};

export default nextConfig;
"""
    (config.frontend_dir / "next.config.monorepo.ts").write_text(content)
    print_info("Created next.config.monorepo.ts with API rewrites")


def _setup_rsbuild_monorepo(config: ProjectConfig) -> None:
    api_url = _api_base_url(config)
    if config.is_nestjs_backend:
        env_content = f"""\
PUBLIC_API_BASE_URL={api_url}
PUBLIC_AUTH_TOKEN_KEY=access_token
PUBLIC_REFRESH_TOKEN_KEY=refresh_token
PUBLIC_ENABLE_MOCK_API=false
"""
    else:
        env_content = f"""\
PUBLIC_API_BASE_URL={api_url}
PUBLIC_AUTH_TOKEN_KEY=access_token
PUBLIC_REFRESH_TOKEN_KEY=refresh_token
PUBLIC_ENABLE_MOCK_API=false
PUBLIC_DJANGO_CSRF_TOKEN_NAME=csrftoken
PUBLIC_DJANGO_STATIC_URL=/static/
PUBLIC_DJANGO_MEDIA_URL=/media/
PUBLIC_DJANGO_API_PREFIX=/api/v1
"""

    (config.frontend_dir / ".env").write_text(env_content)
    (config.frontend_dir / ".env.monorepo").write_text(env_content)
    print_info("Configured Rsbuild frontend for monorepo mode")
    _create_rsbuild_monorepo_config(config)


def _create_rsbuild_monorepo_config(config: ProjectConfig) -> None:
    origin = _backend_origin(config)
    proxy_entries = f"""\
      "/api": {{
        target: "{origin}",
        changeOrigin: true,
      }},"""

    if config.is_django_backend:
        proxy_entries += f"""
      "/static": {{
        target: "{origin}",
        changeOrigin: true,
      }},
      "/media": {{
        target: "{origin}",
        changeOrigin: true,
      }},
      "/admin": {{
        target: "{origin}",
        changeOrigin: true,
      }},"""

    content = f"""\
import {{ defineConfig }} from "@rsbuild/core";
import {{ pluginReact }} from "@rsbuild/plugin-react";

export default defineConfig({{
  plugins: [pluginReact()],
  source: {{
    entry: {{
      index: "./src/main.tsx",
    }},
  }},
  resolve: {{
    alias: {{
      "@": "./src",
    }},
  }},
  server: {{
    port: 3000,
    proxy: {{
{proxy_entries}
    }},
  }},
}});
"""
    (config.frontend_dir / "rsbuild.config.monorepo.ts").write_text(content)
    print_info("Created rsbuild.config.monorepo.ts with API proxy")
