"""Tests for FullstackGenerator — mocked git clone."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

from mattstack.config import ProjectConfig, ProjectType, Variant
from mattstack.generators.fullstack import FullstackGenerator


def _make_config(tmp_path: Path, **kwargs) -> ProjectConfig:
    defaults = {
        "name": "test-proj",
        "path": tmp_path / "test-proj",
        "project_type": ProjectType.FULLSTACK,
        "variant": Variant.STARTER,
        "init_git": False,
    }
    defaults.update(kwargs)
    return ProjectConfig(**defaults)


def _mock_clone(url: str, dest: Path, branch: str = "main", depth: int = 1) -> bool:
    """Simulate a git clone by creating directory with expected files."""
    dest.mkdir(parents=True, exist_ok=True)
    if "django" in url:
        (dest / "pyproject.toml").write_text("[project]\nname = 'test'\n")
        (dest / "manage.py").write_text("#!/usr/bin/env python\n")
        for f in [
            "Makefile",
            "docker-compose.yml",
            ".env",
            ".env.example",
            "Dockerfile",
            "README.md",
            "CLAUDE.md",
            ".gitignore",
            ".dockerignore",
        ]:
            (dest / f).write_text("x")
        (dest / "nginx").mkdir()
    elif "react" in url:
        (dest / "package.json").write_text('{"name": "test"}\n')
        (dest / "src").mkdir()
        for f in [
            "Makefile",
            "docker-compose.yml",
            ".env",
            "env.example",
            "Dockerfile",
            "Dockerfile.dev",
            "README.md",
            "CLAUDE.md",
            ".gitignore",
            ".dockerignore",
        ]:
            (dest / f).write_text("x")
    elif "swift" in url:
        (dest / "Package.swift").write_text("// swift\n")
    return True


@patch("mattstack.generators.base.clone_repo", side_effect=_mock_clone)
def test_fullstack_generates_all_files(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is True
    assert config.path.exists()
    assert (config.path / "Makefile").exists()
    assert (config.path / "docker-compose.yml").exists()
    assert (config.path / "README.md").exists()
    assert (config.path / ".gitignore").exists()
    assert (config.path / ".env.production.example").exists()
    assert (config.path / ".env.production").exists()
    assert (config.path / "tasks" / "todo.md").exists()


@patch("mattstack.generators.base.clone_repo", side_effect=_mock_clone)
def test_fullstack_consolidates_boilerplate_files(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is True
    # Backend standalone files removed (including .env — nothing regenerates it)
    for f in [
        "Makefile",
        "docker-compose.yml",
        ".env",
        "Dockerfile",
        "CLAUDE.md",
        ".gitignore",
    ]:
        assert not (config.backend_dir / f).exists(), f"backend/{f} should be removed"
    # Frontend standalone files removed (.env is regenerated by monorepo setup)
    for f in [
        "Makefile",
        "docker-compose.yml",
        "Dockerfile",
        "CLAUDE.md",
        ".gitignore",
    ]:
        assert not (config.frontend_dir / f).exists(), f"frontend/{f} should be removed"
    # Per-subpackage files preserved
    assert (config.backend_dir / "pyproject.toml").exists()
    assert (config.frontend_dir / "package.json").exists()
    # backend/pyproject.toml declares readme = "README.md"; removing it makes
    # `uv sync` fail, so consolidation keeps the boilerplate README.
    assert (config.backend_dir / "README.md").exists()
    # Relocated Dockerfiles generated
    assert (config.path / "docker" / "backend" / "Dockerfile").exists()
    assert (config.path / "docker" / "frontend" / "Dockerfile").exists()
    assert (config.path / "docker" / "frontend" / "Dockerfile.dev").exists()


@patch("mattstack.generators.base.clone_repo", side_effect=_mock_clone)
def test_fullstack_with_ios(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path, include_ios=True)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is True
    assert (config.path / "ios").exists()


@patch("mattstack.generators.base.clone_repo", return_value=False)
def test_fullstack_clone_failure_returns_false(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is False


@patch("mattstack.generators.base.clone_repo", return_value=False)
def test_fullstack_clone_failure_cleans_up(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path)
    gen = FullstackGenerator(config)
    gen.run()
    # Cleanup should remove the directory
    assert not config.path.exists()


@patch("mattstack.generators.base.clone_repo", side_effect=_mock_clone)
def test_fullstack_b2b(mock_clone, tmp_path: Path) -> None:
    config = _make_config(tmp_path, variant=Variant.B2B)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is True


@patch("mattstack.generators.fullstack.setup_frontend_monorepo")
@patch("mattstack.generators.fullstack.customize_frontend")
@patch("mattstack.generators.fullstack.customize_backend")
@patch("mattstack.generators.base.clone_repo", side_effect=_mock_clone)
def test_fullstack_dry_run(mock_clone, mock_be, mock_fe, mock_setup, tmp_path: Path) -> None:
    config = _make_config(tmp_path, dry_run=True)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is True
    # In dry-run, clone_repo should NOT be called
    mock_clone.assert_not_called()


def test_fullstack_existing_dir_fails(tmp_path: Path) -> None:
    config = _make_config(tmp_path)
    config.path.mkdir(parents=True)
    gen = FullstackGenerator(config)
    result = gen.run()
    assert result is False
