"""Render focused API contract tests for generated CRUD resources."""

from __future__ import annotations

from mattstack.commands.codegen.backend_layout import DJANGO_MATT, BackendLayout
from mattstack.commands.codegen.django_api import KEY_BITS, resource_path
from mattstack.commands.codegen.fields import INT32_MAX, FieldSpec, to_snake

SAMPLE_VALUES: dict[str, object] = {
    "int": 1,
    "float": 1.5,
    "decimal": "9.99",
    "bool": True,
    "date": "2024-01-01",
    "datetime": "2024-01-01T00:00:00Z",
    "email": "test@example.com",
    "url": "https://example.com",
    "uuid": "00000000-0000-0000-0000-000000000001",
}


def _sample(field: FieldSpec) -> object:
    """A valid value; FK samples point at rows that do not exist."""
    if field.is_fk:
        return INT32_MAX if field.fk_key == "int" else KEY_BITS["uuid"][2].replace("0", "1")
    return SAMPLE_VALUES.get(field.type, f"test {field.name}")


def _write_tests(name: str, fields: list[FieldSpec], base: str) -> list[str]:
    """Test a successful write or a missing foreign-key target."""
    payload = {f.api_name: _sample(f) for f in fields}
    post = (
        f'self.client.post("{base}", data=json.dumps(payload), '
        'content_type="application/json", **self.auth)'
    )
    lines: list[str] = []
    if any(f.is_fk for f in fields):
        lines += [
            "",
            "    def test_create_with_missing_relation_returns_404(self) -> None:",
            f"        payload = {payload!r}",
            f"        response = {post}",
            "        assert response.status_code == 404",
            f"        assert {name}.objects.count() == 0",
        ]
    else:
        lines += [
            "",
            "    def test_create_then_get(self) -> None:",
            f"        payload = {payload!r}",
            f"        response = {post}",
            "        assert response.status_code == 201",
            f"        created = self.client.get(f\"{base}{{response.json()['id']}}\")",
            "        assert created.status_code == 200",
        ]
    return lines


def render_api_tests(name: str, fields: list[FieldSpec], layout: BackendLayout) -> str:
    """Render API tests against the real mount prefix and resource path.

    Ninja projects with JWT get a token for a test user; django-matt projects
    with auth only get the unauthenticated checks.
    """
    snake, plural = to_snake(name), resource_path(name)
    base = f"{layout.mount_prefix}{plural}/"
    missing = KEY_BITS[layout.pk_key][2]
    ninja_jwt = layout.has_jwt and layout.framework != DJANGO_MATT
    writes = ninja_jwt or not layout.has_jwt
    imports = ["import json", "", "from django.test import TestCase"]
    if ninja_jwt:
        imports[2:2] = ["from django.contrib.auth import get_user_model"]
        imports.append("from ninja_jwt.tokens import RefreshToken")
    if writes:
        imports += ["", f"from {layout.app_module}.models.{snake} import {name}"]
    lines = [
        f'"""API tests for {name}, generated by mattstack generate crud."""',
        "",
        *imports,
        "",
        "",
        f"class {name}APITest(TestCase):",
    ]
    if ninja_jwt:
        lines += [
            "    def setUp(self) -> None:",
            "        user_model = get_user_model()",
            '        values = {user_model.USERNAME_FIELD: "generated-test@example.com"}',
            '        values.update({f: f"generated-{f}" for f in user_model.REQUIRED_FIELDS})',
            "        user = user_model._default_manager.create(**values)",
            "        token = RefreshToken.for_user(user).access_token",
            '        self.auth = {"HTTP_AUTHORIZATION": f"Bearer {token}"}',
            "",
        ]
    elif not layout.has_jwt:
        lines += ["    auth: dict[str, str] = {}", ""]
    lines += [
        f"    def test_list_{plural}_returns_page(self) -> None:",
        f'        response = self.client.get("{base}")',
        "        assert response.status_code == 200",
        '        assert set(response.json()) >= {"count", "results"}',
        "",
        f"    def test_get_missing_{snake}_returns_404(self) -> None:",
        f'        response = self.client.get("{base}{missing}")',
        "        assert response.status_code == 404",
    ]
    if layout.has_jwt:
        lines += [
            "",
            f"    def test_create_{snake}_requires_auth(self) -> None:",
            f'        response = self.client.post("{base}", data="{{}}", '
            'content_type="application/json")',
            "        assert response.status_code == 401",
            "",
            f"    def test_delete_{snake}_requires_auth(self) -> None:",
            f'        response = self.client.delete("{base}{missing}")',
            "        assert response.status_code == 401",
        ]
    if writes:
        lines += _write_tests(name, fields, base)
    lines.append("")
    return "\n".join(lines)
