"""Render the frontend half of `generate crud`.

Type and function names follow the backend schemas (`ProductResponseSchema`,
`ProductCreateSchema`, ...), keys follow the wire format (FKs as `<name>_id`,
camelCase when the shared transport converts keys), and Decimal is a string.
"""

from __future__ import annotations

from pathlib import Path

from mattstack.commands.codegen.django_api import resource_path
from mattstack.commands.codegen.fields import FieldSpec, search_field, ts_key
from mattstack.commands.codegen.ts_transport import render_request_helper
from mattstack.parsers.frontend_layout import FrontendLayout

HEADER = "// Generated by mattstack generate crud.\n"


def render_ts_types(name: str, fields: list[FieldSpec], camel: bool, id_type: str) -> str:
    def key(field_name: str) -> str:
        return ts_key(field_name, camel)

    def body(optional: bool) -> list[str]:
        mark = "?" if optional else ""
        return [f"  {key(f.api_name)}{mark}: {f.ts_type};" for f in fields]

    blocks = [
        [f"export interface {name}CreateSchema {{", *body(False), "}"],
        [f"export interface {name}UpdateSchema {{", *body(True), "}"],
        [
            f"export interface {name}ResponseSchema extends {name}CreateSchema {{",
            f"  id: {id_type};",
            f"  {key('created_at')}: string;",
            f"  {key('updated_at')}: string;",
            "}",
        ],
        [
            f"export interface {name}Page {{",
            "  count: number;",
            "  next?: string | null;",
            "  previous?: string | null;",
            f"  results: {name}ResponseSchema[];",
            "}",
        ],
    ]
    return "\n\n".join("\n".join(block) for block in blocks) + "\n"


def render_ts_api_client(
    name: str,
    fields: list[FieldSpec],
    layout: FrontendLayout,
    module_file: Path,
    api_prefix: str,
    id_type: str,
) -> str:
    plural = resource_path(name)
    base = f"/{plural}/"
    return (
        HEADER
        + render_request_helper(layout, module_file, api_prefix)
        + "\n"
        + render_ts_types(name, fields, layout.camel_case_keys, id_type)
        + f"""
export function list{name}s(page = 1, pageSize = 20, search?: string): Promise<{name}Page> {{
  return request<{name}Page>("GET", "{base}", {{
    params: {{ page, page_size: pageSize, search }},
  }});
}}

export function get{name}(id: {id_type}): Promise<{name}ResponseSchema> {{
  return request<{name}ResponseSchema>("GET", `{base}${{encodeURIComponent(id)}}`);
}}

export function create{name}(data: {name}CreateSchema): Promise<{name}ResponseSchema> {{
  return request<{name}ResponseSchema>("POST", "{base}", {{ body: data }});
}}

export function update{name}(
  id: {id_type}, data: {name}UpdateSchema,
): Promise<{name}ResponseSchema> {{
  return request<{name}ResponseSchema>(
    "PUT", `{base}${{encodeURIComponent(id)}}`, {{ body: data }},
  );
}}

export function delete{name}(id: {id_type}): Promise<void> {{
  return request<void>("DELETE", `{base}${{encodeURIComponent(id)}}`);
}}
"""
    )


def render_tanstack_hooks(name: str, client_spec: str, id_type: str) -> str:
    key = resource_path(name)
    return f"""{HEADER}import {{
  keepPreviousData, useMutation, useQuery, useQueryClient,
}} from "@tanstack/react-query";

import {{
  create{name},
  delete{name},
  get{name},
  list{name}s,
  update{name},
}} from "{client_spec}";
import type {{ {name}CreateSchema, {name}UpdateSchema }} from "{client_spec}";

export function use{name}List(page = 1, pageSize = 20, search?: string) {{
  return useQuery({{
    queryKey: ["{key}", "list", page, pageSize, search],
    queryFn: () => list{name}s(page, pageSize, search),
    placeholderData: keepPreviousData,
  }});
}}

export function use{name}(id: {id_type}) {{
  return useQuery({{
    queryKey: ["{key}", "detail", id],
    queryFn: () => get{name}(id),
    enabled: Boolean(id),
  }});
}}

export function useCreate{name}() {{
  const queryClient = useQueryClient();
  return useMutation({{
    mutationFn: (data: {name}CreateSchema) => create{name}(data),
    onSuccess: () => queryClient.invalidateQueries({{ queryKey: ["{key}"] }}),
  }});
}}

export function useUpdate{name}() {{
  const queryClient = useQueryClient();
  return useMutation({{
    mutationFn: ({{ id, data }}: {{ id: {id_type}; data: {name}UpdateSchema }}) =>
      update{name}(id, data),
    onSuccess: () => queryClient.invalidateQueries({{ queryKey: ["{key}"] }}),
  }});
}}

export function useDelete{name}() {{
  const queryClient = useQueryClient();
  return useMutation({{
    mutationFn: (id: {id_type}) => delete{name}(id),
    onSuccess: () => queryClient.invalidateQueries({{ queryKey: ["{key}"] }}),
  }});
}}
"""


def render_list_component(
    name: str, fields: list[FieldSpec], hooks_spec: str, use_client: bool, camel: bool
) -> str:
    plural = resource_path(name)
    display = search_field(fields)
    label = f"item.{ts_key(display, camel)}" if display else "item.id"
    directive = '"use client";\n\n' if use_client else ""
    return f"""{directive}{HEADER}import {{ use{name}List }} from "{hooks_spec}";

export function {name}List() {{
  const {{ data, isLoading, error }} = use{name}List();

  if (isLoading) return <div>Loading {plural}...</div>;
  if (error) return <div>Error: {{error.message}}</div>;
  if (!data?.results.length) return <div>No {plural} found.</div>;

  return (
    <ul>
      {{data.results.map((item) => (
        <li key={{item.id}}>{{{label}}}</li>
      ))}}
    </ul>
  );
}}

export default {name}List;
"""


def render_list_page(name: str, component_spec: str, route_id: str | None) -> str:
    """Render the list page: a TanStack file route for *route_id*, else a default export."""
    body = f"""function {name}sPage() {{
  return (
    <div className="container mx-auto p-4">
      <h1>{name}s</h1>
      <{name}List />
    </div>
  );
}}
"""
    if route_id is None:
        return f'{HEADER}import {{ {name}List }} from "{component_spec}";\n\nexport default {body}'
    return (
        f'{HEADER}import {{ createFileRoute }} from "@tanstack/react-router";\n\n'
        f'import {{ {name}List }} from "{component_spec}";\n\n'
        f'export const Route = createFileRoute("{route_id}")({{\n'
        f"  component: {name}sPage,\n}});\n\n{body}"
    )


def render_vitest(name: str, hooks_spec: str) -> str:
    plural = resource_path(name)
    return f"""{HEADER}import {{ render, screen }} from "@testing-library/react";
import {{ beforeEach, describe, expect, it, vi }} from "vitest";

import {{ use{name}List }} from "{hooks_spec}";
import {{ {name}List }} from "./index";

vi.mock("{hooks_spec}", () => ({{ use{name}List: vi.fn() }}));

type ListResult = ReturnType<typeof use{name}List>;
const mockedList = vi.mocked(use{name}List);

function mockList(state: Partial<ListResult>) {{
  const result = {{ data: undefined, isLoading: false, error: null, ...state }};
  mockedList.mockReturnValue(result as unknown as ListResult);
}}

describe("{name}List", () => {{
  beforeEach(() => {{
    mockedList.mockReset();
  }});

  it("renders the empty state", () => {{
    mockList({{ data: {{ count: 0, results: [] }} }});
    render(<{name}List />);
    expect(screen.getByText("No {plural} found.")).toBeDefined();
  }});

  it("renders the loading state", () => {{
    mockList({{ isLoading: true }});
    render(<{name}List />);
    expect(screen.getByText("Loading {plural}...")).toBeDefined();
  }});
}});
"""
