// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Address
 */
export const zAddress = z.object({
    postalCode: z.string().regex(/^[0-9]{5}$/).nullish(),
    streetLine: z.string().min(1).max(120)
});

/**
 * ProductStatus
 */
export const zProductStatus = z.enum([
    'draft',
    'active',
    'archived'
]);

/**
 * Product
 */
export const zProduct = z.object({
    createdAt: z.iso.datetime(),
    displayName: z.string().min(2).max(50),
    kind: z.enum(['physical', 'digital']),
    notes: z.string().nullish(),
    rating: z.number().gt(0).lt(5).nullish(),
    schemaVersion: z.literal('v1').optional().default('v1'),
    shippingAddress: zAddress,
    status: zProductStatus,
    stockCount: z.int().gte(0).lte(1000),
    tags: z.array(z.string()).max(10).optional(),
    unitPrice: z.union([
        z.number().gte(0),
        z.string()
    ])
});

export const zMainCreateProductBody = zProduct;

/**
 * OK
 */
export const zMainCreateProductResponse = zProduct;
