"""Standalone HTML dashboard for a Gauntlet run.

Kept separate from `report.py` so both modules stay well inside the 400-line
file-length gate.
"""

from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path

from mattstack.gauntlet.models import CheckStatus, Finding, RunResult


def generate_html_report(result: RunResult, project_path: Path) -> str:
    """Generate a standalone HTML dashboard for the run."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Audit Report — {escape(project_path.name)}</title>
    <style>{_css()}</style>
</head>
<body>
    {_header(project_path, result)}
    {_summary(result)}
    {_filters()}
    {_table(_build_findings_rows(result.findings))}
    {_skipped_checks(result)}
    <footer>Generated by mattstack audit. Checks by Gauntlet \
{escape(result.gauntlet_version or "unknown")}.</footer>
    <script>{_js()}</script>
</body>
</html>"""


def _css() -> str:
    """Return inline CSS styles."""
    return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #f5f6fa; color: #2d3436; line-height: 1.6; }
        header { background: #2d3436; color: #fff; padding: 2rem; }
        header h1 { font-size: 1.5rem; font-weight: 600; }
        header p { color: #b2bec3; margin-top: 0.25rem; font-size: 0.9rem; }
        .container { max-width: 1200px; margin: 0 auto; padding: 1.5rem; }
        .cards { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
        .card { background: #fff; border-radius: 8px; padding: 1.25rem 1.5rem;
                flex: 1; min-width: 140px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .card .label { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em;
                       color: #636e72; margin-bottom: 0.25rem; }
        .card .value { font-size: 1.75rem; font-weight: 700; }
        .card.total .value { color: #2d3436; }
        .card.error .value { color: #d63031; }
        .card.warning .value { color: #fdcb6e; }
        .card.info .value { color: #0984e3; }
        .filters { margin-bottom: 1rem; display: flex; gap: 0.5rem; flex-wrap: wrap; }
        .filters button { padding: 0.4rem 1rem; border: 1px solid #dfe6e9; border-radius: 4px;
                          background: #fff; cursor: pointer;
                          font-size: 0.85rem; transition: all 0.15s; }
        .filters button:hover { background: #dfe6e9; }
        .filters button.active { background: #2d3436; color: #fff; border-color: #2d3436; }
        table { width: 100%; border-collapse: collapse; background: #fff;
                border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        th { background: #dfe6e9; text-align: left; padding: 0.75rem 1rem; font-size: 0.8rem;
             text-transform: uppercase; letter-spacing: 0.05em; cursor: pointer;
             user-select: none; position: relative; }
        th:hover { background: #b2bec3; }
        th::after { content: ''; display: inline-block; margin-left: 0.4rem; }
        th.sort-asc::after { content: ' ^'; }
        th.sort-desc::after { content: ' v'; }
        td { padding: 0.65rem 1rem; border-top: 1px solid #f1f2f6; font-size: 0.9rem; }
        tr:hover td { background: #fafafa; }
        .badge { display: inline-block; padding: 0.15rem 0.6rem; border-radius: 3px;
                 font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
        .badge-error { background: #fab1a0; color: #d63031; }
        .badge-warning { background: #ffeaa7; color: #e17055; }
        .badge-info { background: #81ecec; color: #00707a; }
        .blocking { color: #d63031; font-weight: 600; }
        .empty-state { text-align: center; padding: 3rem; color: #636e72; }
        .skipped { background: #fff; border-radius: 8px; padding: 1rem 1.5rem;
                   margin-top: 1.5rem; font-size: 0.9rem; color: #636e72; }
        footer { text-align: center; padding: 2rem; color: #b2bec3; font-size: 0.8rem; }
    """


def _header(project_path: Path, result: RunResult) -> str:
    """Build the page header."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""<header>
    <div class="container">
        <h1>Audit Report &mdash; {escape(project_path.name)}</h1>
        <p>{escape(str(project_path))} &middot; {escape(now)} &middot; \
tier {escape(result.tier or "unknown")}</p>
    </div>
</header>"""


def _summary(result: RunResult) -> str:
    """Build the summary cards."""
    return f"""<div class="container">
    <div class="cards">
        <div class="card total">
            <div class="label">Total Findings</div>
            <div class="value">{len(result.findings)}</div>
        </div>
        <div class="card error">
            <div class="label">Errors</div>
            <div class="value">{result.error_count}</div>
        </div>
        <div class="card warning">
            <div class="label">Warnings</div>
            <div class="value">{result.warning_count}</div>
        </div>
        <div class="card info">
            <div class="label">Info</div>
            <div class="value">{result.info_count}</div>
        </div>
    </div>"""


def _filters() -> str:
    """Build the filter buttons."""
    return """<div class="filters">
        <button class="active" data-filter="all">All</button>
        <button data-filter="error">Errors</button>
        <button data-filter="warning">Warnings</button>
        <button data-filter="info">Info</button>
    </div>"""


def _build_findings_rows(findings: list[Finding]) -> str:
    """Build HTML table rows for findings."""
    rows: list[str] = []
    for finding in sorted(findings, key=lambda f: (f.severity.value, f.check, f.location)):
        marker = ' <span class="blocking">blocking</span>' if finding.blocking else ""
        rows.append(
            f'<tr data-severity="{escape(finding.severity.value)}" '
            f'data-category="{escape(finding.category)}">'
            f'<td><span class="badge badge-{escape(finding.severity.value)}">'
            f"{escape(finding.severity.value)}</span></td>"
            f"<td>{escape(finding.category)}</td>"
            f"<td>{escape(finding.location)}</td>"
            f"<td>{escape(finding.title)}{marker}</td>"
            f"<td>{escape(finding.suggested_fix or '')}</td>"
            f"</tr>"
        )
    return "\n".join(rows)


def _table(rows: str) -> str:
    """Build the findings table."""
    if not rows:
        return '<div class="empty-state"><p>No findings. Project looks clean!</p></div></div>'
    return f"""<table id="findings-table">
        <thead>
            <tr>
                <th data-col="0">Severity</th>
                <th data-col="1">Category</th>
                <th data-col="2">Location</th>
                <th data-col="3">Message</th>
                <th data-col="4">Suggestion</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
</div>"""


def _skipped_checks(result: RunResult) -> str:
    """Build the note about checks that did not run."""
    skipped = [c for c in result.checks if c.status == CheckStatus.SKIP]
    if not skipped:
        return ""
    items = "".join(
        f"<li>{escape(c.check)}: {escape(c.note or 'tool not found')}</li>" for c in skipped
    )
    return f'<div class="container"><div class="skipped">Skipped checks<ul>{items}</ul></div></div>'


def _js() -> str:
    """Return inline JavaScript for filtering and sorting."""
    return """
    (function() {
        var buttons = document.querySelectorAll('.filters button');
        buttons.forEach(function(btn) {
            btn.addEventListener('click', function() {
                buttons.forEach(function(b) { b.classList.remove('active'); });
                btn.classList.add('active');
                var filter = btn.getAttribute('data-filter');
                var rows = document.querySelectorAll('#findings-table tbody tr');
                rows.forEach(function(row) {
                    if (filter === 'all' || row.getAttribute('data-severity') === filter) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        });

        var headers = document.querySelectorAll('#findings-table th');
        var sortState = {};
        headers.forEach(function(th) {
            th.addEventListener('click', function() {
                var col = parseInt(th.getAttribute('data-col'));
                var tbody = document.querySelector('#findings-table tbody');
                if (!tbody) return;
                var rows = Array.from(tbody.querySelectorAll('tr'));
                var asc = sortState[col] !== 'asc';
                sortState = {};
                sortState[col] = asc ? 'asc' : 'desc';
                headers.forEach(function(h) { h.classList.remove('sort-asc', 'sort-desc'); });
                th.classList.add(asc ? 'sort-asc' : 'sort-desc');
                rows.sort(function(a, b) {
                    var aText = a.children[col].textContent.toLowerCase();
                    var bText = b.children[col].textContent.toLowerCase();
                    if (aText < bText) return asc ? -1 : 1;
                    if (aText > bText) return asc ? 1 : -1;
                    return 0;
                });
                rows.forEach(function(row) { tbody.appendChild(row); });
            });
        });
    })();
    """
