"""Generate a `gauntlet.toml` for a scaffolded project.

`mattstack init` calls `generate_config` so that every new project has a
working Gauntlet gate from the first commit.

The generated file must stay valid against the schema in
`docs/spec/gauntlet-toml.md` of the Gauntlet repository. Unknown keys are a
hard error there, so do not add a section that the spec does not document.
"""

from __future__ import annotations

from pathlib import Path

CONFIG_FILENAME = "gauntlet.toml"

# Every generated file carries this comment. Update it when the template
# changes in a way that older projects should adopt.
TEMPLATE_VERSION = 1


def _toml_string(value: str) -> str:
    """Quote a value as a TOML basic string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _project_name(project_path: Path) -> str:
    """Return a config name for the project. Falls back to the directory name."""
    return project_path.resolve().name or "project"


def _python_adapter_block(package_manager: str) -> list[str]:
    """Return the `[adapters.python]` block for a Python project."""
    return [
        "[adapters.python]",
        "enabled = true",
        f"package_manager = {_toml_string(package_manager)}",
        'test_runner = "pytest"',
        'lint_tool = "ruff"',
        'type_checker = "mypy"',
        'security_scanner = "bandit"',
        "",
    ]


def _inactive_rust_block(paths: str, note: str) -> list[str]:
    """Return a disabled adapter block to keep the config loadable.

    Gauntlet rejects a config that enables no adapter, and it has no
    TypeScript adapter in the alpha. A disabled Rust block keeps the file
    valid and records why the frontend is outside the gate.
    """
    return [
        note,
        f"# {paths} are outside the gate. Tracked upstream; remove this",
        "# block when the TypeScript adapter ships.",
        "[adapters.rust]",
        "enabled = false",
        "",
    ]


def _rust_adapter_block() -> list[str]:
    """Return the `[adapters.rust]` block for a Rust project."""
    return [
        "[adapters.rust]",
        "enabled = true",
        'coverage_tool = "llvm-cov"',
        "",
    ]


def generate_config(
    project_path: Path,
    *,
    has_python: bool,
    has_typescript: bool,
    has_rust: bool,
    package_manager: str = "uv",
) -> str:
    """Build the text of a `gauntlet.toml` for the detected stack.

    The caller detects the stack; this function only formats the file.
    Exactly one adapter is enabled, so the config is never empty.
    """
    lines: list[str] = [
        "# Gauntlet configuration. Generated by `mattstack init`.",
        f"# Template version {TEMPLATE_VERSION}.",
        "# See https://gauntlet.dev/docs/config for the field reference.",
        "",
        "[project]",
        f"name = {_toml_string(_project_name(project_path))}",
        "schema_version = 1",
        'default_tier = "standard"',
        "",
        "[tiers]",
        'fast.gates = ["deterministic"]',
        'standard.gates = ["deterministic", "conformance"]',
        'full.gates = ["deterministic", "conformance", "review"]',
        'release.gates = ["deterministic", "conformance", "review", "mutation", "perf"]',
        "",
    ]

    if has_python:
        lines.extend(_python_adapter_block(package_manager))
    if has_rust:
        lines.extend(_rust_adapter_block())
    if has_python and has_typescript:
        lines.extend(
            [
                "# The frontend is TypeScript. Gauntlet has no TypeScript adapter",
                "# in the alpha, so those files are outside the gate.",
                "",
            ]
        )
    elif not has_python and not has_rust:
        lines.extend(_inactive_rust_block("frontend files", "# This project has no adapter."))

    lines.extend(
        [
            "# Conformance is optional. Uncomment and set a source when you have",
            "# a plan file you want Gauntlet to check the diff against.",
            "#",
            "# [conformance.plan]",
            '# source = "roadmap"',
            '# path = "docs/ROADMAP.md"',
            "# blocking = true",
            "",
            "[conformance.tickets]",
            'source = "none"',
            "",
            "[checks.deterministic]",
            'enabled = ["all"]',
            "disabled = []",
            "",
            "# Per-check tuning is omitted on purpose. Gauntlet already defaults",
            "# coverage to an 80% advisory threshold, CRAP to 8.0, and TDD to",
            "# advisory, so restating them adds nothing. It also avoids a key",
            "# form that Gauntlet's own spec documents two ways: `[checks.coverage]`",
            "# in gauntlet-toml.md and `[checks.sentinel:coverage]` in init.md.",
            "# An unrecognized key is a hard config error, so do not guess here.",
            "# Raise a threshold once the project has a baseline. See the Gauntlet",
            "# config reference for the accepted key form.",
            "",
            "[review]",
            "enabled = true",
            'backend = "ollama"',
            'model = ""',
            "",
            "[review.routing]",
            'strategy = "capability"',
            "prefer_local = true",
            "fallback_to_cloud = false",
            "",
            "[integrations]",
            'binary_path = "gauntlet"',
            "skip_if_absent = true",
            "",
            "[output]",
            'format = "auto"',
            "rtk_enabled = true",
            "",
            "[budget]",
            "fast_ms = 2000",
            "standard_ms = 30000",
            "full_ms = 300000",
            "",
        ]
    )
    return "\n".join(lines)


def write_config(
    project_path: Path,
    *,
    has_python: bool,
    has_typescript: bool,
    has_rust: bool,
    package_manager: str = "uv",
) -> Path | None:
    """Write `gauntlet.toml` into a scaffolded project.

    Returns the path written, or ``None`` when a config already exists. The
    write follows `gauntlet init`: it never overwrites an existing file.
    """
    destination = project_path / CONFIG_FILENAME
    if destination.exists():
        return None
    content = generate_config(
        project_path,
        has_python=has_python,
        has_typescript=has_typescript,
        has_rust=has_rust,
        package_manager=package_manager,
    )
    destination.write_text(content, encoding="utf-8")
    return destination
