"""Protect command: settings-driven branch protection (design doc §5)."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

import typer
import yaml  # type: ignore[import-untyped]

from mattstack.config_file import load_config
from mattstack.utils.console import print_error, print_info, print_success, print_warning

NO_COMMIT_HOOK = {
    "id": "no-commit-to-branch",
    "args": ["--branch", "main", "--branch", "master"],
}
PRE_COMMIT_HOOKS_REPO = "https://github.com/pre-commit/pre-commit-hooks"
# Status checks required before a merge. GitHub blocks a merge when a
# required check never reports, so this list must name jobs that the
# generated workflow actually emits for every project type.
# `mattstack workflow` emits a block of jobs per project type
# (backend-lint, backend-test, frontend-lint, frontend-test,
# frontend-typecheck), but only `gauntlet` is present in all of them.
DEFAULT_STATUS_CHECKS = ("gauntlet",)


def build_ruleset_payload(required_reviews: int, status_checks: list[str]) -> dict[str, Any]:
    """Build a GitHub branch-protection ruleset payload."""
    return {
        "name": "mattstack-protect-main",
        "target": "branch",
        "enforcement": "active",
        "conditions": {
            "ref_name": {
                "include": ["refs/heads/main", "refs/heads/master"],
                "exclude": [],
            },
        },
        "rules": [
            {"type": "pull_request"},
            {
                "type": "required_reviews",
                "parameters": {"required_approving_review_count": required_reviews},
            },
            {
                "type": "required_status_checks",
                "parameters": {
                    "strict_required_status_checks_policy": False,
                    "required_status_checks": [{"context": c} for c in status_checks],
                },
            },
            {"type": "required_linear_history"},
        ],
    }


def generate_codeowners(owner: str | None) -> str:
    """Return CODEOWNERS content for the given owner (or a placeholder)."""
    if owner:
        return f"# Generated by `mattstack protect` — review before merging.\n* @{owner}\n"
    return (
        "# Generated by `mattstack protect` — replace with your GitHub handle(s).\n"
        "# * @your-github-handle\n"
    )


def _enable_no_commit_to_branch(pre_commit_path: Path, dry_run: bool = False) -> bool:
    """Ensure the no-commit-to-branch hook is active.

    Adds the hook (main + master) to the pre-commit-hooks repo when absent,
    and fixes its args when already present. Returns True when changed.
    """
    try:
        data: Any = yaml.safe_load(pre_commit_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as e:
        print_error(f"Invalid .pre-commit-config.yaml: {e}")
        return False

    if not isinstance(data, dict):
        print_error("Invalid .pre-commit-config.yaml (not a mapping)")
        return False

    repos = data.get("repos")
    if not isinstance(repos, list):
        repos = []
        data["repos"] = repos

    for repo in repos:
        if not isinstance(repo, dict):
            continue
        hooks = repo.get("hooks")
        if not isinstance(hooks, list):
            continue
        for hook in hooks:
            if isinstance(hook, dict) and hook.get("id") == "no-commit-to-branch":
                if hook.get("args") == NO_COMMIT_HOOK["args"]:
                    return False
                hook["args"] = NO_COMMIT_HOOK["args"]
                _dump_pre_commit(pre_commit_path, data, dry_run)
                return True

    target = next(
        (r for r in repos if isinstance(r, dict) and r.get("repo") == PRE_COMMIT_HOOKS_REPO),
        None,
    )
    if target is None:
        target = {"repo": PRE_COMMIT_HOOKS_REPO, "rev": "v5.0.0", "hooks": []}
        repos.append(target)

    hooks = target.setdefault("hooks", [])
    if not isinstance(hooks, list):
        hooks = []
        target["hooks"] = hooks
    hooks.append(dict(NO_COMMIT_HOOK))

    _dump_pre_commit(pre_commit_path, data, dry_run)
    return True


def _dump_pre_commit(path: Path, data: Any, dry_run: bool) -> None:
    if dry_run:
        return
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def _repo_slug(path: Path, gh_bin: str = "gh") -> str | None:
    """Resolve the GitHub owner/repo slug via ``gh repo view``."""
    try:
        result = subprocess.run(
            [gh_bin, "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
            cwd=path,
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    slug = result.stdout.strip()
    return slug or None


def _apply_ruleset(slug: str, payload: dict[str, Any], gh_bin: str = "gh") -> bool:
    """POST a GitHub branch-protection ruleset via the ``gh`` CLI."""
    owner, _, repo = slug.partition("/")
    if not owner or not repo:
        print_error(f"Invalid repo slug: {slug}")
        return False

    endpoint = f"repos/{owner}/{repo}/rulesets"
    try:
        subprocess.run(
            [gh_bin, "api", endpoint, "--method", "POST", "--input", "-"],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to apply ruleset: {e.stderr.strip()}")
        return False
    except FileNotFoundError:
        print_error("`gh` CLI not found — install it to apply the GitHub ruleset")
        return False


def run_protect(path: Path, *, dry_run: bool = False, gh_bin: str = "gh") -> None:
    """Enable branch protection for a project (design doc §5)."""
    path = path.resolve()
    if not path.is_dir():
        print_error(f"Directory not found: {path}")
        raise typer.Exit(code=1)

    config = load_config(path / "mattstack.yml")
    if not config.protect_main:
        print_info("protect_main is false — nothing to do.")
        return

    pre_commit_path = path / ".pre-commit-config.yaml"
    if pre_commit_path.exists():
        if _enable_no_commit_to_branch(pre_commit_path, dry_run=dry_run):
            print_success("Enabled no-commit-to-branch (main/master) in .pre-commit-config.yaml")
        else:
            print_info("no-commit-to-branch already active")
    else:
        print_warning(".pre-commit-config.yaml not found — skipping hook enablement")

    slug = None if dry_run else _repo_slug(path, gh_bin)
    owner = slug.partition("/")[0] if slug else None

    codeowners_path = path / "CODEOWNERS"
    if dry_run:
        print_info(f"Would write CODEOWNERS to {codeowners_path.relative_to(path)}")
    else:
        codeowners_path.write_text(generate_codeowners(owner), encoding="utf-8")
        print_success(f"Wrote {codeowners_path.relative_to(path)}")

    if slug:
        payload = build_ruleset_payload(config.required_reviews, list(DEFAULT_STATUS_CHECKS))
        if dry_run:
            print_info(f"Would apply GitHub ruleset to {slug}")
        elif _apply_ruleset(slug, payload, gh_bin):
            print_success(f"Applied GitHub ruleset to {slug}")
        else:
            raise typer.Exit(code=1)
    else:
        print_warning("Could not determine GitHub repo — skipping ruleset")
