"""Rules command: generate/update AI agent configuration files."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.markup import escape

from mattstack.stack import load_stack, unknown_framework_message
from mattstack.templates.cursorrules import generate_cursorrules
from mattstack.templates.root_claude_md import generate_claude_md
from mattstack.utils.console import console, print_error, print_info, print_success


def _status(file_path: Path) -> str:
    """Return the dry-run status tag, escaped so Rich prints the brackets."""
    return escape("[overwrite]" if file_path.exists() else "[create]")


def run_rules(
    path: Path,
    gsd: bool = False,
    dry_run: bool = False,
    force: bool = False,
) -> None:
    """Generate/update AI agent configuration files.

    The content describes the project's actual stack: persisted metadata in
    mattstack.yml first, manifest detection second. A backend or frontend
    whose framework cannot be determined stops the command, because wrong
    instructions mislead every agent that reads them.
    """
    path = path.resolve()
    if not path.is_dir():
        print_error(f"Directory not found: {path}")
        raise typer.Exit(code=1)

    stack = load_stack(path)
    if not stack.has_backend and not stack.has_frontend:
        print_error(f"No backend or frontend found in {stack.root}")
        raise typer.Exit(code=1)
    unknown = stack.unknown_components()
    if unknown:
        print_error(unknown_framework_message(unknown))
        raise typer.Exit(code=1)

    root = stack.root
    config = stack.config()
    tools = stack.toolchain()

    files_to_write: list[tuple[Path, str, str]] = [
        (
            root / "CLAUDE.md",
            generate_claude_md(config, tools),
            "AI agent context (Claude Code, Cursor)",
        ),
        (root / ".cursorrules", generate_cursorrules(config, tools), "Cursor IDE agent rules"),
    ]

    if gsd:
        from mattstack.templates.gsd_project import (
            generate_gsd_config_json,
            generate_gsd_project_md,
            generate_gsd_state_md,
        )

        planning_dir = root / ".planning"
        files_to_write.extend(
            [
                (
                    planning_dir / "PROJECT.md",
                    generate_gsd_project_md(config, tools),
                    "GSD project definition",
                ),
                (
                    planning_dir / "STATE.md",
                    generate_gsd_state_md(config, tools),
                    "GSD project state",
                ),
                (planning_dir / "config.json", generate_gsd_config_json(), "GSD configuration"),
            ]
        )

    if dry_run:
        console.print()
        console.print("[bold cyan]mattstack rules --dry-run[/bold cyan]")
        console.print()
        for file_path, _, desc in files_to_write:
            rel = escape(str(file_path.relative_to(root)))
            console.print(f"  {_status(file_path)} {rel} — {desc}")
        return

    console.print()
    console.print("[bold cyan]mattstack rules[/bold cyan]")
    console.print()

    for file_path, content, _desc in files_to_write:
        rel = str(file_path.relative_to(root))
        if file_path.exists() and not force:
            print_info(f"Skipping {rel} (exists, use --force to overwrite)")
            continue
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        print_success(f"Generated {rel}")

    if gsd:
        print_info("GSD files created in .planning/")
        print_info("Run /gsd:new-project in Claude Code to start planning")


HARNESS_ADAPTERS: dict[str, str] = {
    "claude": ".claude/CLAUDE.md",
    "cursor": ".cursor/.cursorrules",
    "windsurf": ".windsurf/rules.md",
    "kiro": ".kiro/rules.md",
    "continue": ".continue/README.md",
    "agents": ".agents/AGENTS.md",
}

CANONICAL_DIRS: tuple[str, ...] = (".omp", ".context")

# Files a harness treats as the same instructions as its adapter. Claude Code
# reads ./CLAUDE.md and ./.claude/CLAUDE.md as equivalent project memory
# (https://code.claude.com/docs/en/memory), and `mattstack init`/`rules`
# write ./CLAUDE.md, so syncing the adapter there would duplicate instructions.
EQUIVALENT_FILES: dict[str, str] = {"claude": "CLAUDE.md"}

_GENERATED_HEADER = (
    "<!-- Generated by `mattstack rules sync` from canonical .omp/ + .context/. "
    "Do not edit; regenerate instead. -->"
)


def collect_canonical(path: Path) -> str:
    """Concatenate all ``.md`` files in ``.omp/`` and ``.context/`` in order."""
    chunks: list[str] = []
    for rel in CANONICAL_DIRS:
        directory = path / rel
        if not directory.is_dir():
            continue
        for file in sorted(directory.glob("*.md")):
            chunks.append(f"<!-- {rel}/{file.name} -->\n\n{file.read_text(encoding='utf-8')}")
    return "\n\n".join(chunks)


def render_adapter(canonical: str) -> str:
    """Wrap canonical content with the generated-file header."""
    return f"{_GENERATED_HEADER}\n\n{canonical}\n"


def sync_harness_rules(path: Path, *, dry_run: bool = False, force: bool = False) -> list[Path]:
    """Regenerate per-harness adapters from canonical ``.omp/`` + ``.context/``.

    Returns the list of adapter files written.
    """
    path = path.resolve()
    if not path.is_dir():
        print_error(f"Directory not found: {path}")
        raise typer.Exit(code=1)

    canonical = collect_canonical(path)
    if not canonical.strip():
        print_error(f"No canonical rule files in {path}/.omp/ or {path}/.context/")
        raise typer.Exit(code=1)

    content = render_adapter(canonical)
    written: list[Path] = []

    console.print()
    console.print("[bold cyan]mattstack rules sync[/bold cyan]")
    console.print()

    for harness, rel in HARNESS_ADAPTERS.items():
        target = path / rel
        equivalent = EQUIVALENT_FILES.get(harness)
        if equivalent and (path / equivalent).exists():
            print_info(
                f"Skipping {rel}: {equivalent} already holds the {harness} instructions. "
                f"Delete {equivalent} to use the synced adapter instead."
            )
            continue
        if dry_run:
            console.print(f"  {_status(target)} {escape(rel)} ({escape(harness)})")
            continue
        if target.exists() and not force:
            print_info(f"Skipping {rel} (exists, use --force to overwrite)")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)
        print_success(f"Synced {rel}")

    return written


rules_app = typer.Typer(
    name="rules",
    help="Generate AI agent config files and sync per-harness adapters.",
    no_args_is_help=True,
    rich_markup_mode="rich",
    invoke_without_command=True,
)


@rules_app.callback()
def _rules_callback(
    ctx: typer.Context,
    path: Annotated[Path | None, typer.Option("--path", "-p", help="Project path")] = None,
    gsd: Annotated[
        bool, typer.Option("--gsd", help="Also generate GSD planning files (.planning/)")
    ] = False,
    dry_run: Annotated[
        bool, typer.Option("--dry-run", help="Preview what would be generated")
    ] = False,
    force: Annotated[bool, typer.Option("--force", help="Overwrite existing files")] = False,
) -> None:
    """Generate AI agent config files when invoked without a subcommand."""
    if ctx.invoked_subcommand is None:
        run_rules(path=path or Path.cwd(), gsd=gsd, dry_run=dry_run, force=force)


@rules_app.command("sync")
def sync(
    path: Annotated[Path | None, typer.Option("--path", "-p", help="Project path")] = None,
    dry_run: Annotated[
        bool, typer.Option("--dry-run", help="Preview what would be written")
    ] = False,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite existing adapter files")
    ] = False,
) -> None:
    """Regenerate per-harness adapters from canonical .omp/ + .context/ files."""
    sync_harness_rules(path=path or Path.cwd(), dry_run=dry_run, force=force)
