"""Sync command: generate TypeScript types, Zod schemas, and API client hooks from backend."""

from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Annotated

import typer

from mattstack.parsers.django_routes import Route, find_route_files, parse_routes_file
from mattstack.parsers.python_schemas import (
    PydanticField,
    PydanticSchema,
    PythonEnum,
    find_schema_files,
    parse_enums_file,
    parse_pydantic_file,
)
from mattstack.parsers.utils import find_files
from mattstack.utils.console import console, print_info, print_success, print_warning

sync_app = typer.Typer(
    name="sync",
    help="Generate TypeScript interfaces, Zod schemas, and API client hooks from backend.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)

# Python type → TypeScript type
PYTHON_TO_TS: dict[str, str] = {
    "str": "string",
    "int": "number",
    "float": "number",
    "Decimal": "number",
    "bool": "boolean",
    "date": "string",
    "datetime": "string",
    "UUID": "string",
    "Any": "unknown",
    "bytes": "string",
    # Pydantic types that appear in real schemas. Without these the generator
    # emits the Python name verbatim and the type-check fails on an unknown
    # name.
    "EmailStr": "string",
    "AnyUrl": "string",
    "HttpUrl": "string",
    "FileUrl": "string",
    "PostgresDsn": "string",
    "RedisDsn": "string",
    "SecretStr": "string",
    "SecretBytes": "string",
    "IPvAnyAddress": "string",
    "timedelta": "string",
    "Json": "unknown",
    "PositiveInt": "number",
    "NegativeInt": "number",
    "NonNegativeInt": "number",
    "NonPositiveInt": "number",
    "StrictStr": "string",
    "StrictInt": "number",
    "StrictFloat": "number",
    "StrictBool": "boolean",
}

# Python type → Zod type constructor
PYTHON_TO_ZOD: dict[str, str] = {
    "str": "z.string()",
    "int": "z.number().int()",
    "float": "z.number()",
    "Decimal": "z.number()",
    "bool": "z.boolean()",
    "date": "z.string()",
    "datetime": "z.string()",
    "UUID": "z.string().uuid()",
    "Any": "z.unknown()",
    "bytes": "z.string()",
    "EmailStr": "z.string().email()",
    "AnyUrl": "z.string().url()",
    "HttpUrl": "z.string().url()",
    "FileUrl": "z.string()",
    "PostgresDsn": "z.string()",
    "RedisDsn": "z.string()",
    "SecretStr": "z.string()",
    "SecretBytes": "z.string()",
    "IPvAnyAddress": "z.string()",
    "timedelta": "z.string()",
    "Json": "z.unknown()",
    "PositiveInt": "z.number().int().positive()",
    "NegativeInt": "z.number().int().negative()",
    "NonNegativeInt": "z.number().int().nonnegative()",
    "NonPositiveInt": "z.number().int().nonpositive()",
    "StrictStr": "z.string()",
    "StrictInt": "z.number().int()",
    "StrictFloat": "z.number()",
    "StrictBool": "z.boolean()",
}

# Pydantic constraint → Zod method
CONSTRAINT_TO_ZOD: dict[str, str] = {
    "min_length": ".min({value})",
    "max_length": ".max({value})",
    "gt": ".gt({value})",
    "lt": ".lt({value})",
    "pattern": ".regex(new RegExp({value}))",
    "regex": ".regex(new RegExp({value}))",
}

LIST_RE = re.compile(r"^list\[(.+)\]$", re.IGNORECASE)
DICT_RE = re.compile(r"^dict\[(.+?),\s*(.+)\]$", re.IGNORECASE)

PYTHON_PATTERNS = ["**/*.py"]

GENERATED_HEADER = "// Auto-generated by mattstack sync types — do not edit\n"
ZOD_HEADER = "// Auto-generated by mattstack sync zod — do not edit\n"
API_HEADER = "// Auto-generated by mattstack sync api-client — do not edit\n"


def _snake_to_camel(name: str) -> str:
    """Convert snake_case to camelCase."""
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _split_top_level_union(type_str: str) -> list[str]:
    """Split on `|` that sits outside brackets.

    A naive split breaks `dict[str, bool | str]`, where the bar belongs to the
    inner type. Only a bar at bracket depth zero separates union members.
    """
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for char in type_str:
        if char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
        if char == "|" and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(char)
    parts.append("".join(current).strip())
    return [part for part in parts if part]


def _resolve_ts_type(type_str: str) -> str:
    """Map a Python type string to a TypeScript type string."""
    type_str = type_str.strip()

    # Top-level union: `dict[str, Any] | None` becomes
    # `Record<string, unknown> | null`. Optional[...] was already unwrapped.
    members = _split_top_level_union(type_str)
    if len(members) > 1:
        resolved: list[str] = []
        for member in members:
            mapped = _resolve_ts_type(member)
            if mapped not in resolved:
                resolved.append(mapped)
        return " | ".join(resolved)

    # list[X] → X[]
    list_match = LIST_RE.match(type_str)
    if list_match:
        inner = _resolve_ts_type(list_match.group(1).strip())
        return f"{inner}[]"

    # dict[K, V] → Record<K, V>
    dict_match = DICT_RE.match(type_str)
    if dict_match:
        key = _resolve_ts_type(dict_match.group(1).strip())
        val = _resolve_ts_type(dict_match.group(2).strip())
        return f"Record<{key}, {val}>"

    # A bare container has no element type to carry over, and TypeScript has
    # no `list`, `set`, or `tuple` name.
    if type_str in (
        "list",
        "List",
        "set",
        "Set",
        "tuple",
        "Tuple",
        "Sequence",
        "Iterable",
    ):
        return "unknown[]"

    if type_str in ("dict", "Dict", "Mapping", "object"):
        return "Record<string, unknown>"

    if type_str == "None":
        return "null"

    # Strip a module qualifier so `uuid.UUID` and `datetime.datetime` resolve
    # the same as their bare names.
    short = type_str.rsplit(".", 1)[-1]
    if short == "None":
        return "null"
    return PYTHON_TO_TS.get(short, short)


def _resolve_zod_type(type_str: str) -> str:
    """Map a Python type string to a Zod schema constructor."""
    list_match = LIST_RE.match(type_str)
    if list_match:
        inner = _resolve_zod_type(list_match.group(1).strip())
        return f"z.array({inner})"

    dict_match = DICT_RE.match(type_str)
    if dict_match:
        key = _resolve_zod_type(dict_match.group(1).strip())
        val = _resolve_zod_type(dict_match.group(2).strip())
        return f"z.record({key}, {val})"

    if type_str.lower() == "dict":
        return "z.record(z.string(), z.unknown())"

    short = type_str.rsplit(".", 1)[-1]
    return PYTHON_TO_ZOD.get(short, f"z.unknown() /* {type_str} */")


def _apply_zod_constraints(base: str, constraints: dict[str, str]) -> str:
    """Append Zod constraint methods based on Pydantic Field constraints."""
    result = base
    for key, value in constraints.items():
        template = CONSTRAINT_TO_ZOD.get(key)
        if template:
            result += template.format(value=value)
    return result


def _field_to_ts(field: PydanticField, use_camel: bool) -> str:
    """Convert a PydanticField to a TypeScript interface field line."""
    name = _snake_to_camel(field.api_name) if use_camel else field.api_name
    ts_type = _resolve_ts_type(field.type_str)
    optional = "?" if field.optional else ""
    null_suffix = " | null" if field.optional and "null" not in ts_type else ""
    return f"  {name}{optional}: {ts_type}{null_suffix}"


def _field_to_zod(field: PydanticField, use_camel: bool) -> str:
    """Convert a PydanticField to a Zod schema field line."""
    name = _snake_to_camel(field.api_name) if use_camel else field.api_name
    zod_type = _resolve_zod_type(field.type_str)
    zod_type = _apply_zod_constraints(zod_type, field.constraints)
    if field.optional:
        zod_type = f"{zod_type}.nullable().optional()"
    return f"  {name}: {zod_type}"


def _schema_to_interface(schema: PydanticSchema) -> str:
    """Convert a PydanticSchema to a TypeScript interface string."""
    use_camel = schema.alias_generator in ("to_camel", "to_lower_camel")
    lines = [f"export interface {schema.name} {{"]
    for field in schema.fields:
        lines.append(f"{_field_to_ts(field, use_camel)};")
    lines.append("}")
    return "\n".join(lines)


def _schema_name_to_var(name: str) -> str:
    """Convert PascalCase schema name to camelCase variable name for Zod."""
    if not name:
        return name
    return name[0].lower() + name[1:]


def _schema_to_zod(schema: PydanticSchema) -> str:
    """Convert a PydanticSchema to a Zod schema string."""
    use_camel = schema.alias_generator in ("to_camel", "to_lower_camel")
    var_name = f"{_schema_name_to_var(schema.name)}Schema"
    lines = [f"export const {var_name} = z.object({{"]
    for field in schema.fields:
        lines.append(f"{_field_to_zod(field, use_camel)},")
    lines.append("})")
    lines.append("")
    lines.append(f"export type {schema.name} = z.infer<typeof {var_name}>")
    return "\n".join(lines)


def _collect_schemas(project_path: Path) -> list[PydanticSchema]:
    """Scan backend directory for Pydantic schemas."""
    backend_dir = project_path / "backend"
    if not backend_dir.is_dir():
        # Fall back to project root
        backend_dir = project_path

    schema_files = find_schema_files(backend_dir)
    if not schema_files:
        return []

    schemas: list[PydanticSchema] = []
    seen: set[str] = set()
    for f in schema_files:
        for schema in parse_pydantic_file(f):
            # A base class with no fields of its own, such as a shared
            # CamelCaseSchema, would duplicate its own subclasses.
            if not schema.fields:
                continue
            # Several boilerplate modules define the same schema name, and
            # TypeScript errors when two interfaces with one name differ.
            if schema.name in seen:
                continue
            seen.add(schema.name)
            schemas.append(schema)
    return schemas


def _collect_routes(project_path: Path) -> list[Route]:
    """Scan backend directory for Django routes."""
    backend_dir = project_path / "backend"
    if not backend_dir.is_dir():
        backend_dir = project_path

    route_files = find_route_files(backend_dir)
    if not route_files:
        return []

    routes: list[Route] = []
    for f in route_files:
        routes.extend(parse_routes_file(f))
    return routes


def _collect_enums(project_path: Path) -> list[PythonEnum]:
    """Scan the backend for Python enums referenced by schemas."""
    backend_dir = project_path / "backend"
    if not backend_dir.is_dir():
        backend_dir = project_path

    enums: list[PythonEnum] = []
    seen: set[str] = set()
    for f in find_files(backend_dir, PYTHON_PATTERNS):
        for enum in parse_enums_file(f):
            if enum.name not in seen:
                seen.add(enum.name)
                enums.append(enum)
    return enums


def _enum_to_union(enum: PythonEnum) -> str:
    """Render a Python enum as a TypeScript string union."""
    if not enum.values:
        return f"export type {enum.name} = string"
    members = " | ".join(f'"{value}"' for value in enum.values)
    return f"export type {enum.name} = {members}"


def _infer_response_type(route: Route) -> str | None:
    """Infer response type name from function name convention."""
    name = route.function_name
    # list_users → User, get_user → User, create_user → User
    for prefix in ("list_", "get_", "create_", "update_", "delete_", "patch_"):
        if name.startswith(prefix):
            resource = name[len(prefix) :]
            # Singularize: remove trailing 's' for list endpoints
            if prefix == "list_" and resource.endswith("s"):
                resource = resource[:-1]
            # snake_case → PascalCase
            return "".join(part.capitalize() for part in resource.split("_"))
    return None


API_ERROR_INTERFACE = """\
export interface ApiError {
  message: string
  status: number
  detail?: string | Record<string, string[]>
}"""


def _pascal_to_snake(name: str) -> str:
    """Convert PascalCase to snake_case (e.g. Product → product, OrderItem → order_item)."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def _route_to_hooks(route: Route, known_types: set[str]) -> list[str]:
    """Generate TanStack Query hooks from a Route. Returns 1-2 hooks (list → also paginated)."""
    response_type = _infer_response_type(route)
    func_name = route.function_name
    hook_name = "use" + "".join(part.capitalize() for part in func_name.split("_"))

    # Build path, replacing {param} with template literal
    path = route.path
    path_params = re.findall(r"\{(\w+)\}", path)
    ts_path = re.sub(r"\{(\w+)\}", r"${\1}", path) if path_params else path

    param_sig = ", ".join(f"{p}: string" for p in path_params)
    path_expr = f"`{ts_path}`" if path_params else f"'{path}'"

    hooks: list[str] = []

    if route.method == "GET":
        is_list = func_name.startswith("list_")
        type_annotation = ""
        if response_type and response_type in known_types:
            type_annotation = f"<{response_type}{'[]' if is_list else ''}>"

        query_key = [f"'{func_name}'"]
        if path_params:
            query_key.extend(path_params)
        key_str = ", ".join(query_key)

        lines = [
            f"export function {hook_name}({param_sig}) {{",
            "  return useQuery({",
            f"    queryKey: [{key_str}],",
            f"    queryFn: () => apiClient.get{type_annotation}({path_expr}).then(r => r.data),",
            "  })",
            "}",
        ]
        hooks.append("\n".join(lines))

        # Paginated variant for list endpoints (only when type is known)
        if is_list and response_type and response_type in known_types:
            resource_snake = func_name[len("list_") :]  # e.g. "products"
            paginated_name = f"use{response_type}List"
            base_path = path.rstrip("/")
            paginated_path = f"{base_path}/?page=${{page}}&page_size=${{pageSize}}"
            paginated_lines = [
                f"export function {paginated_name}(page: number = 1, pageSize: number = 20) {{",
                "  return useQuery({",
                f"    queryKey: ['{resource_snake}', page, pageSize],",
                f"    queryFn: () => apiClient.get{type_annotation}("
                f"`{paginated_path}`).then(r => r.data),  # noqa: E501"
                "    placeholderData: keepPreviousData,",
                "  })",
                "}",
            ]
            hooks.append("\n".join(paginated_lines))

    else:
        # POST, PUT, DELETE, PATCH → useMutation with onSuccess invalidation
        mutation_method = route.method.lower()

        # Infer request body type from CreateSchema/UpdateSchema naming conventions
        input_type: str | None = None
        if response_type and route.method in ("POST", "PUT", "PATCH"):
            for suffix in ("CreateSchema", "UpdateSchema", "Create", "Update", "Input"):
                candidate = f"{response_type}{suffix}"
                if candidate in known_types:
                    input_type = candidate
                    break

        type_annotation = ""
        if response_type and response_type in known_types:
            type_annotation = f"<{response_type}>"

        # Derive cache key to invalidate (e.g. Product → 'products')
        invalidate_key = f"'{_pascal_to_snake(response_type)}s'" if response_type else "''"

        if route.method == "DELETE":
            lines = [
                f"export function {hook_name}({param_sig}) {{",
                "  const queryClient = useQueryClient()",
                "  return useMutation({",
                f"    mutationFn: () => apiClient.delete({path_expr}),",
                "    onSuccess: () => {",
                f"      queryClient.invalidateQueries({{ queryKey: [{invalidate_key}] }})",
                "    },",
                "  })",
                "}",
            ]
        else:
            data_param = f"data: {input_type}" if input_type else "data: unknown"
            all_params = [data_param] + [f"{p}: string" for p in path_params]
            full_sig = ", ".join(all_params)
            lines = [
                f"export function {hook_name}({full_sig}) {{",
                "  const queryClient = useQueryClient()",
                "  return useMutation({",
                f"    mutationFn: () => apiClient.{mutation_method}{type_annotation}"
                f"({path_expr}, data).then(r => r.data),",
                "    onSuccess: () => {",
                f"      queryClient.invalidateQueries({{ queryKey: [{invalidate_key}] }})",
                "    },",
                "  })",
                "}",
            ]
        hooks.append("\n".join(lines))

    return hooks


def _write_output(content: str, output_path: Path, dry_run: bool) -> None:
    """Write content to file or print to console for dry-run."""
    if dry_run:
        console.print(f"\n[dim]--- {output_path} ---[/dim]")
        console.print(content)
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print_success(f"Wrote {output_path}")


@sync_app.command("types")
def sync_types(
    path: Annotated[
        Path,
        typer.Option("--path", "-p", help="Project root directory"),
    ] = Path("."),
    output: Annotated[
        str | None,
        typer.Option("--output", "-o", help="Output file path"),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Preview without writing"),
    ] = False,
) -> None:
    """Generate TypeScript interfaces from Pydantic models."""
    start = time.monotonic()
    project_path = path.resolve()

    schemas = _collect_schemas(project_path)
    if not schemas:
        print_warning("No Pydantic schemas found in backend")
        raise typer.Exit(code=0)

    lines = [GENERATED_HEADER, ""]
    # A schema field can reference an enum. TypeScript cannot resolve a name
    # that was never emitted, so emit every enum first.
    for enum in _collect_enums(project_path):
        lines.append(_enum_to_union(enum))
        lines.append("")
    for schema in schemas:
        lines.append(_schema_to_interface(schema))
        lines.append("")

    content = "\n".join(lines)
    output_path = (
        Path(output) if output else project_path / "frontend" / "src" / "types" / "generated.ts"
    )

    _write_output(content, output_path, dry_run)

    elapsed = time.monotonic() - start
    print_info(f"Generated {len(schemas)} interfaces in {elapsed:.2f}s")


@sync_app.command("zod")
def sync_zod(
    path: Annotated[
        Path,
        typer.Option("--path", "-p", help="Project root directory"),
    ] = Path("."),
    output: Annotated[
        str | None,
        typer.Option("--output", "-o", help="Output file path"),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Preview without writing"),
    ] = False,
) -> None:
    """Generate Zod validation schemas from Pydantic models."""
    start = time.monotonic()
    project_path = path.resolve()

    schemas = _collect_schemas(project_path)
    if not schemas:
        print_warning("No Pydantic schemas found in backend")
        raise typer.Exit(code=0)

    lines = [ZOD_HEADER, "", "import { z } from 'zod'", ""]
    for schema in schemas:
        lines.append(_schema_to_zod(schema))
        lines.append("")

    content = "\n".join(lines)
    output_path = (
        Path(output) if output else project_path / "frontend" / "src" / "schemas" / "generated.ts"
    )

    _write_output(content, output_path, dry_run)

    elapsed = time.monotonic() - start
    print_info(f"Generated {len(schemas)} Zod schemas in {elapsed:.2f}s")


@sync_app.command("api-client")
def sync_api_client(
    path: Annotated[
        Path,
        typer.Option("--path", "-p", help="Project root directory"),
    ] = Path("."),
    output: Annotated[
        str | None,
        typer.Option("--output", "-o", help="Output file path"),
    ] = None,
    base_url: Annotated[
        str,
        typer.Option("--base-url", help="API base URL for generated client"),
    ] = "http://localhost:8000",
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Preview without writing"),
    ] = False,
) -> None:
    """Generate typed TanStack Query hooks from Django routes."""
    start = time.monotonic()
    project_path = path.resolve()

    routes = _collect_routes(project_path)
    if not routes:
        print_warning("No routes found in backend")
        raise typer.Exit(code=0)

    schemas = _collect_schemas(project_path)
    known_types = {s.name for s in schemas}

    hooks: list[str] = []
    referenced_types: set[str] = set()
    has_mutations = False
    has_paginated = False

    for route in routes:
        if route.is_stub:
            continue
        route_hooks = _route_to_hooks(route, known_types)
        for hook in route_hooks:
            hooks.append(hook)
            for t in known_types:
                if t in hook:
                    referenced_types.add(t)
            if "useMutation" in hook:
                has_mutations = True
            if "keepPreviousData" in hook:
                has_paginated = True

    if not hooks:
        print_warning("No non-stub routes found to generate hooks")
        raise typer.Exit(code=0)

    tanstack_imports = ["useQuery"]
    if has_mutations:
        tanstack_imports.extend(["useMutation", "useQueryClient"])
    if has_paginated:
        tanstack_imports.append("keepPreviousData")

    import_lines = [
        API_HEADER,
        f"// Base URL: {base_url}",
        "",
        f"import {{ {', '.join(tanstack_imports)} }} from '@tanstack/react-query'",
        "import { apiClient } from '@/api/client'",
    ]
    if referenced_types:
        sorted_types = sorted(referenced_types)
        type_imports = ", ".join(sorted_types)
        import_lines.append(f"import type {{ {type_imports} }} from '@/types/generated'")

    import_lines.extend(["", API_ERROR_INTERFACE, ""])

    content = "\n".join(import_lines) + "\n" + "\n\n".join(hooks) + "\n"
    output_path = (
        Path(output) if output else project_path / "frontend" / "src" / "api" / "generated.ts"
    )

    _write_output(content, output_path, dry_run)

    elapsed = time.monotonic() - start
    print_info(f"Generated {len(hooks)} API hooks in {elapsed:.2f}s")


@sync_app.command("all")
def sync_all(
    path: Annotated[
        Path,
        typer.Option("--path", "-p", help="Project root directory"),
    ] = Path("."),
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Preview without writing"),
    ] = False,
) -> None:
    """Run types + zod + api-client in sequence."""
    start = time.monotonic()
    project_path = path.resolve()

    # Types
    console.rule("[bold cyan]TypeScript Interfaces")
    schemas = _collect_schemas(project_path)
    if schemas:
        lines = [GENERATED_HEADER, ""]
        for schema in schemas:
            lines.append(_schema_to_interface(schema))
            lines.append("")
        types_path = project_path / "frontend" / "src" / "types" / "generated.ts"
        _write_output("\n".join(lines), types_path, dry_run)
        print_info(f"{len(schemas)} interfaces")
    else:
        print_warning("No Pydantic schemas found")

    # Zod
    console.rule("[bold cyan]Zod Schemas")
    if schemas:
        lines = [ZOD_HEADER, "", "import { z } from 'zod'", ""]
        for schema in schemas:
            lines.append(_schema_to_zod(schema))
            lines.append("")
        zod_path = project_path / "frontend" / "src" / "schemas" / "generated.ts"
        _write_output("\n".join(lines), zod_path, dry_run)
        print_info(f"{len(schemas)} Zod schemas")
    else:
        print_warning("No schemas to generate Zod from")

    # API Client
    console.rule("[bold cyan]API Client Hooks")
    routes = _collect_routes(project_path)
    known_types = {s.name for s in schemas} if schemas else set()
    hooks: list[str] = []
    referenced_types: set[str] = set()
    has_mutations = False
    has_paginated = False

    for route in routes:
        if route.is_stub:
            continue
        for hook in _route_to_hooks(route, known_types):
            hooks.append(hook)
            for t in known_types:
                if t in hook:
                    referenced_types.add(t)
            if "useMutation" in hook:
                has_mutations = True
            if "keepPreviousData" in hook:
                has_paginated = True

    if hooks:
        tanstack_imports = ["useQuery"]
        if has_mutations:
            tanstack_imports.extend(["useMutation", "useQueryClient"])
        if has_paginated:
            tanstack_imports.append("keepPreviousData")

        import_lines = [
            API_HEADER,
            "",
            f"import {{ {', '.join(tanstack_imports)} }} from '@tanstack/react-query'",
            "import { apiClient } from '@/api/client'",
        ]
        if referenced_types:
            sorted_types = sorted(referenced_types)
            type_imports = ", ".join(sorted_types)
            import_lines.append(f"import type {{ {type_imports} }} from '@/types/generated'")
        import_lines.extend(["", API_ERROR_INTERFACE, ""])

        content = "\n".join(import_lines) + "\n" + "\n\n".join(hooks) + "\n"
        api_path = project_path / "frontend" / "src" / "api" / "generated.ts"
        _write_output(content, api_path, dry_run)
        print_info(f"{len(hooks)} API hooks")
    else:
        print_warning("No routes found to generate hooks")

    elapsed = time.monotonic() - start
    console.rule("[bold green]Done")
    total_count = (len(schemas) if schemas else 0) * 2 + len(hooks)
    print_success(f"Synced {total_count} total artifacts in {elapsed:.2f}s")
