"""Sync command: generate TypeScript types, Zod schemas, and API client hooks from backend."""

from __future__ import annotations

import time
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated

import typer

from mattstack.commands.codegen.backend_layout import (
    GenerateError,
    find_api_instance,
    find_mount_prefix,
)
from mattstack.commands.codegen.ts_hooks import render_hooks
from mattstack.commands.codegen.ts_schemas import (
    SchemaSet,
    collect_schema_set,
    render_types_file,
)
from mattstack.commands.codegen.ts_transport import render_request_helper
from mattstack.commands.codegen.ts_zod import render_zod_file
from mattstack.parsers.api_routes import collect_api_routes
from mattstack.parsers.frontend_layout import FrontendLayout, detect_frontend_layout
from mattstack.utils.console import console, print_info, print_success, print_warning

sync_app = typer.Typer(
    name="sync",
    help="Generate TypeScript interfaces, Zod schemas, and API client hooks from backend.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)

GENERATED_HEADER = "// Auto-generated by mattstack sync types — do not edit\n"
ZOD_HEADER = "// Auto-generated by mattstack sync zod — do not edit\n"
API_HEADER = "// Auto-generated by mattstack sync api-client — do not edit\n"

PathOption = Annotated[Path, typer.Option("--path", "-p", help="Project root directory")]
OutputOption = Annotated[str | None, typer.Option("--output", "-o", help="Output file path")]
DryRunOption = Annotated[bool, typer.Option("--dry-run", help="Preview without writing")]


@dataclass(frozen=True)
class SyncContext:
    backend_dir: Path
    layout: FrontendLayout
    api_prefix: str  # where the backend mounts its API, e.g. "/api"

    @property
    def types_path(self) -> Path:
        return self.layout.src_dir / "types" / "generated.ts"

    @property
    def zod_path(self) -> Path:
        return self.layout.src_dir / "schemas" / "generated.ts"

    @property
    def api_path(self) -> Path:
        return self.layout.src_dir / "api" / "generated.ts"


def _context(path: Path) -> SyncContext:
    from mattstack.project import resolve_project
    from mattstack.templates.frontend_runtime import api_base_env_var

    try:
        project = resolve_project(path.resolve())
    except ValueError as exc:
        raise typer.BadParameter(str(exc)) from exc
    backend_dir = project.backend_dir if project.backend_dir.is_dir() else project.root
    try:
        api_file, api_var, _ = find_api_instance(backend_dir)
        api_prefix = find_mount_prefix(backend_dir, api_file, api_var).rstrip("/")
    except GenerateError:
        api_prefix = project.api_prefix.rstrip("/")
    env_var = api_base_env_var(project.config) if project.frontend_framework else None
    layout = detect_frontend_layout(project.frontend_dir, env_var)
    return SyncContext(backend_dir, layout, api_prefix)


def _schemas(ctx: SyncContext) -> SchemaSet:
    schema_set = collect_schema_set(ctx.backend_dir)
    for warning in schema_set.warnings:
        print_warning(warning)
    return schema_set


def render_api_client(ctx: SyncContext, schema_set: SchemaSet, output: Path) -> tuple[str, int]:
    """Render the hooks module for every non-stub route; return (source, hook count)."""
    request_names = schema_set.request_names
    known = schema_set.names | schema_set.enum_names
    hook_set = render_hooks(collect_api_routes(ctx.backend_dir), known, request_names)
    known |= set(request_names.values())
    if not hook_set.hooks:
        return "", 0
    lines = [API_HEADER]
    lines.append(
        f'import {{ {", ".join(sorted(hook_set.tanstack))} }} from "@tanstack/react-query";'
    )
    used = sorted(hook_set.used_types & known)
    if used:
        spec = ctx.layout.import_path(output, ctx.types_path)
        lines.append(f'import type {{ {", ".join(used)} }} from "{spec}";')
    lines.append(render_request_helper(ctx.layout, output, ctx.api_prefix))
    for interface in hook_set.page_interfaces():
        lines += [interface, ""]
    return "\n".join(lines) + "\n" + "\n\n".join(hook_set.hooks) + "\n", len(hook_set.hooks)


def _write_output(content: str, output_path: Path, dry_run: bool) -> None:
    """Write content to file or print it for dry-run."""
    if dry_run:
        console.print(f"\n--- {output_path} ---", markup=False, style="dim")
        console.print(content, markup=False, highlight=False)
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print_success(f"Wrote {output_path}")


def _emit_types(ctx: SyncContext, schema_set: SchemaSet, output: Path, dry_run: bool) -> None:
    content = render_types_file(schema_set, GENERATED_HEADER, ctx.layout.camel_case_keys)
    _write_output(content, output, dry_run)


def _emit_zod(ctx: SyncContext, schema_set: SchemaSet, output: Path, dry_run: bool) -> None:
    content = render_zod_file(schema_set, ZOD_HEADER, ctx.layout.camel_case_keys)
    _write_output(content, output, dry_run)


@sync_app.command("types")
def sync_types(
    path: PathOption = Path("."), output: OutputOption = None, dry_run: DryRunOption = False
) -> None:
    """Generate TypeScript interfaces and enum unions from Pydantic models."""
    start = time.monotonic()
    ctx = _context(path)
    schema_set = _schemas(ctx)
    if not schema_set.schemas:
        print_warning("No Pydantic schemas found in backend")
        raise typer.Exit(code=0)
    _emit_types(ctx, schema_set, Path(output) if output else ctx.types_path, dry_run)
    print_info(f"Generated {len(schema_set.schemas)} interfaces in {time.monotonic() - start:.2f}s")


@sync_app.command("zod")
def sync_zod(
    path: PathOption = Path("."), output: OutputOption = None, dry_run: DryRunOption = False
) -> None:
    """Generate Zod validation schemas and enums from Pydantic models."""
    start = time.monotonic()
    ctx = _context(path)
    schema_set = _schemas(ctx)
    if not schema_set.schemas:
        print_warning("No Pydantic schemas found in backend")
        raise typer.Exit(code=0)
    _emit_zod(ctx, schema_set, Path(output) if output else ctx.zod_path, dry_run)
    print_info(
        f"Generated {len(schema_set.schemas)} Zod schemas in {time.monotonic() - start:.2f}s"
    )


@sync_app.command("api-client")
def sync_api_client(
    path: PathOption = Path("."), output: OutputOption = None, dry_run: DryRunOption = False
) -> None:
    """Generate typed TanStack Query hooks from Django routes."""
    start = time.monotonic()
    ctx = _context(path)
    out = Path(output).resolve() if output else ctx.api_path
    content, count = render_api_client(ctx, _schemas(ctx), out)
    if not count:
        print_warning("No non-stub routes found to generate hooks")
        raise typer.Exit(code=0)
    _write_output(content, out, dry_run)
    print_info(f"Generated {count} API hooks in {time.monotonic() - start:.2f}s")


@sync_app.command("all")
def sync_all(path: PathOption = Path("."), dry_run: DryRunOption = False) -> None:
    """Run types + zod + api-client with the same output as each command alone."""
    start = time.monotonic()
    ctx = _context(path)
    schema_set = _schemas(ctx)
    count = 0
    console.rule("TypeScript Interfaces")
    if schema_set.schemas:
        _emit_types(ctx, schema_set, ctx.types_path, dry_run)
        console.rule("Zod Schemas")
        _emit_zod(ctx, schema_set, ctx.zod_path, dry_run)
        count += 2 * len(schema_set.schemas)
    else:
        print_warning("No Pydantic schemas found")
    console.rule("API Client Hooks")
    content, hooks = render_api_client(ctx, schema_set, ctx.api_path)
    if hooks:
        _write_output(content, ctx.api_path, dry_run)
        count += hooks
    else:
        print_warning("No routes found to generate hooks")
    console.rule("Done")
    print_success(f"Synced {count} total artifacts in {time.monotonic() - start:.2f}s")
