"""Production entrypoint for the backend image (``docker/backend/entrypoint.sh``).

The script checks the runtime contract from ``deploy_runtime`` before any
process starts, so a provider that lacks a variable fails with the variable
name, the reason, the provider-specific fix, and a local verify command. It
never derives a value: provider ``DATABASE_URL`` strings are not parsed into
``DB_*`` and no secret has a fallback.

Modes: ``serve`` (default CMD) starts the framework server on ``$PORT``;
``migrate`` applies migrations; ``check`` runs the checks and exits; any other
command (a worker, ``python manage.py ...``) runs after the checks.
"""

from __future__ import annotations

from mattstack.config import DeploymentTarget, ProjectConfig
from mattstack.templates.deploy_runtime import (
    PLACEHOLDER_PREFIX,
    EnvRequirement,
    distinct_secrets,
    health_path,
    production_mode_env,
    required_env,
    set_instruction,
    tls_env,
    verify_command,
)


def generate_backend_entrypoint(config: ProjectConfig) -> str:
    """Generate the POSIX shell entrypoint for the production backend image."""
    reqs = required_env(config)
    runtime = [line for req in reqs if not req.web_only for line in _checks(config, req)]
    runtime.extend(_mode_checks(config))
    runtime.extend(_distinct_checks(config))
    web = [line for req in reqs if req.web_only for line in _checks(config, req)]
    web.extend(_tls_checks(config))
    return f"""\
#!/bin/sh
# Generated by mattstack: production entrypoint for the backend image.
# Modes: serve (default), migrate, check, health. Any other command runs after the checks.
set -eu

# APP_PORT pins the port where a platform sets PORT for another container.
PORT="${{APP_PORT:-${{PORT:-{config.backend_api_port}}}}}"
export PORT
failures=0

report() {{
    failures=$((failures + 1))
    printf 'preflight: %s\\n  why: %s\\n  fix: %s\\n' "$1" "$2" "$3" >&2
}}

check_runtime() {{
{_body(runtime)}
}}

check_web() {{
{_body(web)}
}}

finish() {{
    if [ "$failures" -gt 0 ]; then
        printf 'preflight: %s problem(s); nothing was started.\\n  verify: %s\\n' \\
            "$failures" {_dq(verify_command(config))} >&2
        exit 1
    fi
}}

# Container health probe: sends a Host Django accepts and the edge's scheme,
# so ALLOWED_HOSTS and the TLS redirect stay in force for real traffic.
if [ "${{1:-}}" = health ]; then
{_health(config)}
fi

check_runtime
case "${{1:-serve}}" in
    serve)
        check_web
{_platform_hosts(config)}        finish
        exec {_serve(config)}
        ;;
    migrate)
        finish
        exec {_migrate(config)}
        ;;
    check)
        check_web
        finish
        echo "preflight: ok"
        ;;
    *)
        finish
        exec "$@"
        ;;
esac
"""


def _serve(config: ProjectConfig) -> str:
    if config.is_nestjs_backend:
        # package.json start:prod runs `node dist/main`; oven/bun maps node to bun.
        return "bun run start:prod"
    if config.is_fastapi_backend:
        return 'uvicorn app.main:app --host 0.0.0.0 --port "$PORT" --workers 4'
    if config.is_django_matt:
        return (
            f"granian --interface asgi {config.wsgi_app}.asgi:application "
            '--host 0.0.0.0 --port "$PORT" --workers 3'
        )
    return f'gunicorn {config.wsgi_app}.wsgi:application --bind "0.0.0.0:$PORT" --workers 3'


def _health(config: ProjectConfig) -> str:
    """Probe the local server the way the edge would reach it."""
    url = f"http://127.0.0.1:$PORT{health_path(config)}"
    if config.is_nestjs_backend:
        # The bun image has no curl.
        script = (
            f"const r = await fetch('http://127.0.0.1:' + process.env.PORT + "
            f"'{health_path(config)}'); process.exit(r.ok ? 0 : 1)"
        )
        return f'    exec bun -e "{script}"'
    if not config.is_django_backend:
        return f'    exec curl -fsS -o /dev/null "{url}"'
    # Django rejects a Host outside ALLOWED_HOSTS; use the first configured
    # host (a leading-dot domain matches itself) and the edge's https scheme.
    return "\n".join(
        [
            '    hosts="${ALLOWED_HOSTS:-}"',
            '    host="$(printf %s "${hosts%%,*}" | tr -d " ")"',
            '    host="${host#.}"',
            "    case \"$host\" in ''|'*') host=localhost ;; esac",
            '    exec curl -fsS -o /dev/null -H "Host: $host" '
            f'-H "X-Forwarded-Proto: https" "{url}"',
        ]
    )


def _platform_hosts(config: ProjectConfig) -> str:
    """Allow the Hosts a platform's own health checks send, and nothing broader.

    - Render: the service's onrender.com host (exported as
      RENDER_EXTERNAL_HOSTNAME) and ``localhost``, which Render's port
      detector sends as ``localhost:$PORT``
      (community.render.com/t/health-check-invalid-http-host-header-localhost-10000/4438).
    - An ALB health check sends the target IP. With
      ALLOWED_HOSTS_INCLUDE_TASK_IP=true the entrypoint appends that address,
      read from the ECS task metadata endpoint.
    """
    if not config.is_django_backend:
        return ""
    if config.deployment == DeploymentTarget.RENDER:
        return "\n".join(
            [
                '        if [ -n "${RENDER:-}" ]; then',
                '            ALLOWED_HOSTS="${ALLOWED_HOSTS:-},localhost"',
                '            if [ -n "${RENDER_EXTERNAL_HOSTNAME:-}" ]; then',
                '                ALLOWED_HOSTS="$ALLOWED_HOSTS,$RENDER_EXTERNAL_HOSTNAME"',
                "            fi",
                "            export ALLOWED_HOSTS",
                "        fi",
                "",
            ]
        )
    if config.deployment != DeploymentTarget.AWS:
        return ""
    reader = (
        "import json, os, urllib.request; "
        "url = os.environ['ECS_CONTAINER_METADATA_URI_V4']; "
        "meta = json.load(urllib.request.urlopen(url)); "
        "print(meta['Networks'][0]['IPv4Addresses'][0])"
    )
    fix = "run on ECS (ECS_CONTAINER_METADATA_URI_V4 is set) or unset ALLOWED_HOSTS_INCLUDE_TASK_IP"
    return "\n".join(
        [
            '        if [ "${ALLOWED_HOSTS_INCLUDE_TASK_IP:-}" = true ]; then',
            f'            if task_ip="$(python -c "{reader}")" && [ -n "$task_ip" ]; then',
            '                ALLOWED_HOSTS="${ALLOWED_HOSTS:-},$task_ip"',
            "                export ALLOWED_HOSTS",
            "            else",
            f"                report {_dq('The ECS task IP could not be read.')} "
            f"{_dq('ALB health checks send the task IP as Host.')} {_dq(fix)}",
            "            fi",
            "        fi",
            "",
        ]
    )


def _tls_checks(config: ProjectConfig) -> list[str]:
    lines: list[str] = []
    for name, value in tls_env(config).items():
        why = "The edge serves HTTPS; Django enables HSTS, secure cookies, and the redirect."
        lines.extend(
            [
                f'if [ "${{{name}:-}}" != {_dq(value)} ]; then',
                f"    report {_dq(f'{name} must be {value}.')} {_dq(why)} "
                f"{_dq(set_instruction(config, name))}",
                "fi",
            ]
        )
    return lines


def _migrate(config: ProjectConfig) -> str:
    if config.is_nestjs_backend:
        return "bun run db:migrate"
    if config.is_fastapi_backend:
        return "alembic upgrade head"
    return "python manage.py migrate --noinput"


def _checks(config: ProjectConfig, req: EnvRequirement) -> list[str]:
    name = req.name
    ref = f'"${{{name}:-}}"'
    fix = set_instruction(config, name)
    lines = [
        f"if [ -z {ref} ]; then",
        f"    report {_dq(f'{name} is not set.')} {_dq(req.why)} {_dq(fix)}",
        "fi",
        # A platform reference the provider did not resolve arrives verbatim.
        f"case {ref} in",
        "    *'${'*)",
        f"        report {_dq(f'{name} holds an unresolved platform reference.')} "
        f"{_dq('The provider passed its reference syntax through instead of a value.')} "
        f"{_dq(fix)}",
        "        ;;",
        "esac",
    ]
    if req.secret:
        lines.extend(
            [
                f"case {ref} in",
                f"    {PLACEHOLDER_PREFIX}*)",
                f"        report {_dq(f'{name} still holds a generated placeholder.')} "
                f"{_dq('Placeholders from .env.production.example are public values.')} "
                f"{_dq(fix)}",
                "        ;;",
                "esac",
            ]
        )
    if req.rejected:
        lines.extend(
            [
                f"case {ref} in",
                f"    {'|'.join(req.rejected)})",
                f"        report {_dq(f'{name} holds a known default value.')} "
                f"{_dq(req.why)} {_dq(fix)}",
                "        ;;",
                "esac",
            ]
        )
    if req.min_length:
        lines.extend(
            [
                f'if [ -n {ref} ] && [ "${{#{name}}}" -lt {req.min_length} ]; then',
                f"    report {_dq(f'{name} is shorter than {req.min_length} characters.')} "
                f"{_dq(req.why)} {_dq(fix)}",
                "fi",
            ]
        )
    if req.prefixes:
        allowed = "|".join(f"{prefix}*" for prefix in req.prefixes)
        expected = " or ".join(req.prefixes)
        lines.extend(
            [
                f"case {ref} in",
                f"    ''|{allowed}) ;;",
                "    *)",
                f"        report {_dq(f'{name} must start with {expected}.')} "
                f"{_dq(req.why)} {_dq(fix)}",
                "        ;;",
                "esac",
            ]
        )
    return lines


def _mode_checks(config: ProjectConfig) -> list[str]:
    lines: list[str] = []
    for name, value in production_mode_env(config).items():
        why = f"The production image sets {name}={value}; another value changes the runtime mode."
        fix = f"remove the {name} override from the provider environment or set it to {value}"
        lines.extend(
            [
                f'if [ "${{{name}:-}}" != {_dq(value)} ]; then',
                f"    report {_dq(f'{name} must be {value}.')} {_dq(why)} {_dq(fix)}",
                "fi",
            ]
        )
    return lines


def _distinct_checks(config: ProjectConfig) -> list[str]:
    names = distinct_secrets(config)
    lines: list[str] = []
    for index, first in enumerate(names):
        for second in names[index + 1 :]:
            why = "Each secret signs different data; a shared value makes one leak expose both."
            fix = set_instruction(config, second)
            lines.extend(
                [
                    f'if [ -n "${{{first}:-}}" ] && [ "${{{first}:-}}" = "${{{second}:-}}" ]; then',
                    f"    report {_dq(f'{first} and {second} hold the same value.')} "
                    f"{_dq(why)} {_dq(fix)}",
                    "fi",
                ]
            )
    return lines


def _body(lines: list[str]) -> str:
    if not lines:
        return "    :"
    return "\n".join(f"    {line}" for line in lines)


def _dq(text: str) -> str:
    """Quote ``text`` for a POSIX shell double-quoted string."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return '"' + escaped.replace("`", "\\`") + '"'
