"""Hetzner (or any Docker host) behind Caddy with automatic HTTPS.

``docker-compose.caddy.yml`` extends the generated ``docker-compose.prod.yml``
instead of replacing it, so the services, secrets, and task workers keep a
single definition. The override stops publishing the app ports (Compose
``!reset``) and puts Caddy on 80/443. ``DOMAIN`` has no default.
"""

from __future__ import annotations

from mattstack.config import DeploymentTarget, ProjectConfig
from mattstack.runtime_profiles import task_processes
from mattstack.templates.compose_env import required
from mattstack.templates.deploy_runtime import compose_command, edge_backend_paths, tls_env
from mattstack.templates.frontend_runtime import FRONTEND_PORT

ENV_FILE = ".env.production"


def unpublish_app_ports(config: ProjectConfig) -> list[str]:
    """Stop publishing the base app ports; the API learns that the edge serves TLS."""
    lines = ["services:"]
    if config.has_backend:
        lines.extend(["  api:", "    ports: !reset []"])
        tls = tls_env(config)
        if tls:
            # Merged into the base service's environment mapping.
            lines.append("    environment:")
            lines.extend(f'      {key}: "{value}"' for key, value in tls.items())
    if config.has_frontend:
        lines.extend(["  frontend:", "    ports: !reset []"])
    return lines


def serves_frontend(config: ProjectConfig) -> bool:
    """Cloudflare Pages hosts the frontend, so the Docker host serves only the API."""
    return config.has_frontend and config.deployment != DeploymentTarget.CLOUDFLARE


def proxy_depends(config: ProjectConfig) -> list[str]:
    deps = (["api"] if config.has_backend else []) + (
        ["frontend"] if serves_frontend(config) else []
    )
    return ["    depends_on:", *(f"      - {dep}" for dep in deps)]


def frontend_port(config: ProjectConfig) -> int:
    """Next.js serves on 3000; the static frontends serve through nginx on 80."""
    return FRONTEND_PORT if config.is_nextjs else 80


def up_command(config: ProjectConfig) -> str:
    """Start the stack; with Pages hosting the frontend, start only the backend services."""
    if serves_frontend(config) or not config.has_frontend:
        return f"{compose_command(config)} up -d --build"
    services = ["caddy", *(p.service for p in task_processes(config, production=True))]
    return f"{compose_command(config)} up -d --build {' '.join(services)}"


def generate_caddy_compose(config: ProjectConfig) -> str:
    """Generate docker-compose.caddy.yml."""
    lines = [
        "# Generated by mattstack. Start the stack behind Caddy:",
        f"#   {up_command(config)}",
        "# Apply migrations:",
        f"#   {compose_command(config)} run --rm api migrate",
        *unpublish_app_ports(config),
        "  caddy:",
        "    image: caddy:2-alpine",
        "    restart: unless-stopped",
        "    environment:",
        f'      DOMAIN: "{required("DOMAIN", ENV_FILE)}"',
        "    ports:",
        '      - "80:80"',
        '      - "443:443"',
        '      - "443:443/udp"',
        "    volumes:",
        "      - ./Caddyfile:/etc/caddy/Caddyfile:ro",
        "      - caddy_data:/data",
        "      - caddy_config:/config",
        *proxy_depends(config),
        "",
        "volumes:",
        "  caddy_data:",
        "  caddy_config:",
    ]
    return "\n".join(lines) + "\n"


def generate_caddyfile(config: ProjectConfig) -> str:
    """Generate the Caddyfile; Caddy reads ``{$DOMAIN}`` from its environment.

    The static frontend image proxies the API itself, so Caddy sends it all
    traffic. In front of Next.js, Caddy routes the backend paths directly.
    """
    upstream = f"api:{config.backend_api_port}"
    frontend = f"frontend:{frontend_port(config)}"
    lines = ["{$DOMAIN} {"]
    if not serves_frontend(config):
        lines.append(f"    reverse_proxy {upstream}")
    elif config.has_backend and config.is_nextjs:
        matchers = " ".join(f"{p} {p}/*" for p in edge_backend_paths(config))
        lines.extend(
            [
                f"    @backend path {matchers}",
                "    handle @backend {",
                f"        reverse_proxy {upstream}",
                "    }",
                "    handle {",
                f"        reverse_proxy {frontend}",
                "    }",
            ]
        )
    else:
        lines.append(f"    reverse_proxy {frontend}")
    lines.append("}")
    return "\n".join(lines) + "\n"
