"""Cloudflare Pages configuration (``wrangler.toml``) for static frontends.

Pages serves the Vite or Rsbuild ``dist`` output. Pages cannot proxy the API
prefix to another origin, so a full-stack build bakes the absolute HTTPS API
base into the bundle at build time. The backend runs on a Docker host from
``docker-compose.prod.yml`` behind the Caddy override, which terminates TLS:
an HTTPS page cannot call a plain-HTTP API (mixed content).
``unsupported_deployment_reason`` rejects a backend-only project and Next.js.
"""

from __future__ import annotations

from mattstack.config import ProjectConfig
from mattstack.templates.deploy_hetzner import (
    generate_caddy_compose,
    generate_caddyfile,
    up_command,
)
from mattstack.templates.deploy_runtime import compose_command
from mattstack.templates.frontend_runtime import api_base_env_var, api_prefix


def cloudflare_files(config: ProjectConfig) -> dict[str, str]:
    files = {"wrangler.toml": generate_wrangler_toml(config)}
    if config.has_backend:
        files["docker-compose.caddy.yml"] = generate_caddy_compose(config)
        files["Caddyfile"] = generate_caddyfile(config)
    return files


def generate_wrangler_toml(config: ProjectConfig) -> str:
    """Generate wrangler.toml for ``wrangler pages deploy``."""
    lines = [
        "# Generated by mattstack. Reference:",
        "# https://developers.cloudflare.com/pages/functions/wrangler-configuration/",
        "# Build and deploy (authenticated):",
    ]
    if config.has_backend:
        build_env = f"{api_base_env_var(config)}=https://<api-domain>{api_prefix(config)}"
        lines.extend(
            [
                f"#   (cd frontend && {build_env} bun run build)",
                f"#   bunx wrangler pages deploy --project-name {config.name}",
                "# The backend runs on a Docker host; Caddy serves it over HTTPS at",
                "# DOMAIN=<api-domain> (set DOMAIN in .env.production):",
                f"#   {up_command(config)}",
                f"#   {compose_command(config)} run --rm api migrate",
                "# Include <api-domain> in the backend's ALLOWED_HOSTS (Django) and allow",
                "# the Pages origin in its CORS origins (and CSRF_TRUSTED_ORIGINS for Django).",
            ]
        )
    else:
        lines.extend(
            [
                "#   (cd frontend && bun run build)",
                f"#   bunx wrangler pages deploy --project-name {config.name}",
            ]
        )
    lines.extend(
        [
            f'name = "{config.name}"',
            'pages_build_output_dir = "frontend/dist"',
            'compatibility_date = "2024-01-01"',
        ]
    )
    return "\n".join(lines) + "\n"
