"""Render Blueprint (``render.yaml``).

The backend runs the generated production image (``runtime: docker``), so
Render builds the last Dockerfile stage. Database settings use the discrete
``fromDatabase`` properties (``host``, ``port``, ``user``, ``password``,
``database``) instead of parsing ``connectionString``. Signing secrets use
``generateValue``, which creates one independent random value per key;
workers copy them from the API service with ``fromService.envVarKey``.
Operator values are ``sync: false``: Render asks for them on the first
Blueprint sync, and the image entrypoint reports any that are missing.
"""

from __future__ import annotations

from mattstack.config import ProjectConfig
from mattstack.runtime_profiles import task_processes
from mattstack.templates.deploy_runtime import (
    BACKEND_DOCKERFILE,
    ENTRYPOINT,
    FRONTEND_DOCKERFILE,
    MIGRATE_COMMAND,
    EnvRequirement,
    api_service,
    distinct_secrets,
    edge_backend_paths,
    health_path,
    required_env,
    tls_env,
)
from mattstack.templates.frontend_runtime import browser_env

_DB_PROPERTIES = {
    "DB_NAME": "database",
    "DB_USER": "user",
    # Database property name, not a credential value.
    "DB_PASSWORD": "password",  # nosec B105
    "DB_HOST": "host",
    "DB_PORT": "port",
}
_REDIS_NAMES = ("REDIS_URL", "CELERY_BROKER_URL", "CELERY_RESULT_BACKEND")


def generate_render_yaml(config: ProjectConfig) -> str:
    """Generate render.yaml."""
    services: list[str] = []
    header = "# Generated by mattstack. Spec: https://render.com/docs/blueprint-spec\n"
    if config.has_backend:
        processes = task_processes(config, production=True)
        services.append(_api(config))
        services.extend(_worker(config, p.service, f"{ENTRYPOINT} {p.command}") for p in processes)
        if config.use_redis:
            # A task broker must not lose queued messages to eviction.
            policy = "noeviction" if processes else "allkeys-lru"
            services.append(
                f"""\
  - type: redis
    name: {config.name}-redis
    plan: starter
    ipAllowList: []
    maxmemoryPolicy: {policy}"""
            )
    if config.has_frontend:
        services.append(_frontend(config))
    result = header + "services:\n" + "\n\n".join(services)
    if config.has_backend:
        result += f"""

databases:
  - name: {config.name}-db
    databaseName: {config.python_package_name}
    user: {config.python_package_name}
    plan: basic-256mb
    ipAllowList: []"""
    return result + "\n"


def _api(config: ProjectConfig) -> str:
    api = api_service(config)
    lines = [_env_var(config, req, source=None) for req in required_env(config)]
    lines.extend(
        f'      - key: {key}\n        value: "{value}"' for key, value in tls_env(config).items()
    )
    env = "\n".join(lines)
    return f"""\
  - type: web
    name: {api}
    runtime: docker
    plan: starter
    dockerfilePath: ./{BACKEND_DOCKERFILE}
    dockerContext: .
    preDeployCommand: {MIGRATE_COMMAND}
    healthCheckPath: {health_path(config)}
    envVars:
{env}"""


def _worker(config: ProjectConfig, name: str, command: str) -> str:
    api = api_service(config)
    env = "\n".join(
        _env_var(config, req, source=api) for req in required_env(config) if not req.web_only
    )
    return f"""\
  - type: worker
    name: {config.name}-{name}
    runtime: docker
    plan: starter
    dockerfilePath: ./{BACKEND_DOCKERFILE}
    dockerContext: .
    dockerCommand: {command}
    envVars:
{env}"""


def _env_var(config: ProjectConfig, req: EnvRequirement, *, source: str | None) -> str:
    key = f"      - key: {req.name}"
    if req.name in _DB_PROPERTIES:
        return f"""{key}
        fromDatabase:
          name: {config.name}-db
          property: {_DB_PROPERTIES[req.name]}"""
    if req.name == "DATABASE_URL" and config.is_nestjs_backend:
        # env.validation.ts accepts the postgresql:// scheme Render provides.
        return f"""{key}
        fromDatabase:
          name: {config.name}-db
          property: connectionString"""
    if req.name in _REDIS_NAMES and config.use_redis:
        return f"""{key}
        fromService:
          type: redis
          name: {config.name}-redis
          property: connectionString"""
    if source is not None:
        return f"""{key}
        fromService:
          type: web
          name: {source}
          envVarKey: {req.name}"""
    if req.name in distinct_secrets(config) or req.name == "SECRET_KEY":
        # One independent random value per key, so the signing secrets differ.
        return f"{key}\n        generateValue: true"
    return f"{key}\n        sync: false"


def _frontend(config: ProjectConfig) -> str:
    name = f"{config.name}-frontend"
    if config.is_nextjs:
        # Frontend-only Next.js; the full-stack combination is rejected earlier.
        return f"""\
  - type: web
    name: {name}
    runtime: docker
    plan: starter
    dockerfilePath: ./{FRONTEND_DOCKERFILE}
    dockerContext: .
    healthCheckPath: /"""
    lines = [
        "  - type: web",
        f"    name: {name}",
        "    runtime: static",
        "    buildCommand: cd frontend && bun install --frozen-lockfile && bun run build",
        "    staticPublishPath: frontend/dist",
    ]
    if config.has_backend:
        # The bundle calls the relative API prefix, as in development. The
        # rewrite forwards it to the API service. Render names the host
        # <service>.onrender.com unless the name is taken; confirm it in the
        # Dashboard after the first sync and edit the destination if it differs.
        lines.append("    envVars:")
        for key, value in browser_env(config).items():
            lines.extend([f"      - key: {key}", f"        value: {value}"])
        # Django admin, static (WhiteNoise), and media also live on the API.
        host = f"https://{api_service(config)}.onrender.com"
        lines.append("    routes:")
        for path in edge_backend_paths(config):
            lines.extend(
                [
                    "      - type: rewrite",
                    f"        source: {path}/*",
                    f"        destination: {host}{path}/*",
                ]
            )
    else:
        lines.append("    routes:")
    lines.extend(
        [
            "      - type: rewrite",
            "        source: /*",
            "        destination: /index.html",
        ]
    )
    return "\n".join(lines)
