"""Self-hosted Docker host behind nginx with Let's Encrypt (certbot) and systemd.

``docker-compose.nginx.yml`` extends the generated ``docker-compose.prod.yml``
like the Hetzner override. nginx renders ``nginx.conf.template`` with
``DOMAIN`` at startup (the official image substitutes only defined
variables, so ``$host`` stays an nginx variable). nginx refuses to start
without a certificate, so the header gives the one-time issuance command.
"""

from __future__ import annotations

from mattstack.config import ProjectConfig
from mattstack.templates.compose_env import required
from mattstack.templates.deploy_hetzner import (
    ENV_FILE,
    frontend_port,
    proxy_depends,
    unpublish_app_ports,
)
from mattstack.templates.deploy_runtime import compose_command, edge_backend_paths


def generate_nginx_compose(config: ProjectConfig) -> str:
    """Generate docker-compose.nginx.yml."""
    compose = compose_command(config)
    lines = [
        "# Generated by mattstack. Issue the first certificate (port 80 must be free):",
        f"#   {compose} run --rm -p 80:80 --entrypoint certbot certbot certonly \\",
        '#     --standalone -d "$DOMAIN" -m "$LETSENCRYPT_EMAIL" --agree-tos --no-eff-email',
        "# Start the stack and apply migrations:",
        f"#   {compose} up -d --build",
        f"#   {compose} run --rm api migrate",
        "# Reload nginx after certbot renews a certificate:",
        f"#   {compose} exec nginx nginx -s reload",
        *unpublish_app_ports(config),
        "  nginx:",
        "    image: nginx:alpine",
        "    restart: unless-stopped",
        "    environment:",
        f'      DOMAIN: "{required("DOMAIN", ENV_FILE)}"',
        "    ports:",
        '      - "80:80"',
        '      - "443:443"',
        "    volumes:",
        "      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro",
        "      - ./certbot/conf:/etc/letsencrypt:ro",
        "      - ./certbot/www:/var/www/certbot:ro",
        *proxy_depends(config),
        "  certbot:",
        "    image: certbot/certbot",
        "    restart: unless-stopped",
        "    entrypoint: \"/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot"
        " -w /var/www/certbot; sleep 12h & wait $${!}; done'\"",
        "    volumes:",
        "      - ./certbot/conf:/etc/letsencrypt",
        "      - ./certbot/www:/var/www/certbot",
    ]
    return "\n".join(lines) + "\n"


def _location(path: str, upstream: str) -> list[str]:
    return [
        f"    location {path} {{",
        f"        proxy_pass http://{upstream};",
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        "    }",
    ]


def generate_nginx_conf(config: ProjectConfig) -> str:
    """Generate nginx.conf.template for the reverse proxy."""
    cert_dir = "/etc/letsencrypt/live/${DOMAIN}"
    lines = [
        "server {",
        "    listen 80;",
        "    server_name ${DOMAIN};",
        "",
        "    location /.well-known/acme-challenge/ {",
        "        root /var/www/certbot;",
        "    }",
        "",
        "    location / {",
        "        return 301 https://$host$request_uri;",
        "    }",
        "}",
        "",
        "server {",
        "    listen 443 ssl;",
        "    server_name ${DOMAIN};",
        f"    ssl_certificate {cert_dir}/fullchain.pem;",
        f"    ssl_certificate_key {cert_dir}/privkey.pem;",
        "",
    ]
    api = f"api:{config.backend_api_port}"
    frontend = f"frontend:{frontend_port(config)}"
    if not config.has_frontend:
        lines.extend(_location("/", api))
    elif config.has_backend and config.is_nextjs:
        # Next.js rewrites only the API prefix; route the backend paths here.
        for path in edge_backend_paths(config):
            lines.extend(_location(f"= {path}", api))
            lines.extend(_location(f"^~ {path}/", api))
        lines.extend(_location("/", frontend))
    else:
        # The static frontend image proxies the API, admin, static, and media.
        lines.extend(_location("/", frontend))
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate_systemd_service(config: ProjectConfig) -> str:
    """Generate a systemd unit that runs the Compose stack from /opt/<name>."""
    compose = compose_command(config).replace("docker compose", "/usr/bin/docker compose", 1)
    return f"""\
[Unit]
Description={config.display_name} Application
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/{config.name}
ExecStart={compose} up -d
ExecStop={compose} down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
"""
