"""DigitalOcean App Platform spec (``.do/app.yaml``).

The API, workers, and the pre-deploy migration job build the generated
production image from the repository root. Database settings use the
documented bindables (``${db.HOSTNAME}``, ``${db.PORT}``, ``${db.USERNAME}``,
``${db.PASSWORD}``, ``${db.DATABASE}``), so no URL is parsed. Operator values
are app-level ``SECRET`` envs without a value; App Platform passes app-level
variables to every component, so components do not repeat them.

With a static frontend, the frontend image (nginx) receives all traffic and
proxies the API prefix and the Django admin, media, and static paths to
``${api.PRIVATE_URL}``. Next.js bakes its rewrite target at build time, when
bindables are unavailable, so App Platform routes the backend paths to the API
directly with ``preserve_path_prefix``.

Reference: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
"""

from __future__ import annotations

from mattstack.config import ProjectConfig
from mattstack.runtime_profiles import task_processes
from mattstack.templates.deploy_runtime import (
    BACKEND_DOCKERFILE,
    ENTRYPOINT,
    FRONTEND_DOCKERFILE,
    MIGRATE_COMMAND,
    EnvRequirement,
    edge_backend_paths,
    health_path,
    required_env,
    tls_env,
)
from mattstack.templates.frontend_runtime import FRONTEND_PORT, api_prefix

_DB = "db"  # Component names stay short: bindable prefixes allow 32 characters.
_API = "api"
_BINDABLE = {
    "DB_NAME": "DATABASE",
    "DB_USER": "USERNAME",
    # Bindable field name, not a credential value.
    "DB_PASSWORD": "PASSWORD",  # nosec B105
    "DB_HOST": "HOSTNAME",
    "DB_PORT": "PORT",
}


def generate_do_app_spec(config: ProjectConfig) -> str:
    """Generate .do/app.yaml."""
    lines = [
        "# Generated by mattstack. Replace OWNER/REPO with the GitHub repository.",
        "# Validate: doctl apps spec validate --schema-only .do/app.yaml",
        "# Set each app-level SECRET value before the first deploy (Control Panel >",
        "# Settings > App-Level Environment Variables), then run:",
        "#   doctl apps create --spec .do/app.yaml",
        f"name: {config.name}",
        "region: nyc",
    ]
    if config.has_backend:
        operator = [req for req in required_env(config) if _value(config, req) is None]
        if operator:
            lines.append("envs:")
            for req in operator:
                lines.extend([f"  - key: {req.name}", "    scope: RUN_TIME", "    type: SECRET"])
    services: list[str] = []
    if config.has_backend:
        services.append(_api(config))
    if config.has_frontend and (config.has_backend or config.is_nextjs):
        services.append(_frontend_service(config))
    if services:
        lines.append("services:")
        lines.extend(services)
    if config.has_frontend and not config.has_backend and not config.is_nextjs:
        lines.extend(["static_sites:", _static()])
    if config.has_backend:
        processes = task_processes(config, production=True)
        if processes:
            lines.append("workers:")
            for process in processes:
                lines.extend(_component(process.service))
                lines.append(f"    run_command: {ENTRYPOINT} {process.command}")
                lines.extend(_envs(config, web=False))
        lines.append("jobs:")
        lines.extend(_component("migrate"))
        lines.extend(["    kind: PRE_DEPLOY", f"    run_command: {MIGRATE_COMMAND}"])
        lines.extend(_envs(config, web=False))
        lines.extend(
            [
                "databases:",
                f"  - name: {_DB}",
                "    engine: PG",
                "    version: '16'",
                "    production: false",
            ]
        )
    return "\n".join(lines) + "\n"


def _component(name: str, dockerfile: str = BACKEND_DOCKERFILE) -> list[str]:
    return [
        f"  - name: {name}",
        "    github:",
        "      repo: OWNER/REPO",
        "      branch: main",
        "      deploy_on_push: true",
        "    source_dir: /",
        f"    dockerfile_path: {dockerfile}",
        "    instance_count: 1",
        "    instance_size_slug: basic-xxs",
    ]


def _api(config: ProjectConfig) -> str:
    lines = _component(_API)
    port = config.backend_api_port
    lines.extend([f"    http_port: {port}", "    health_check:"])
    if not config.is_django_backend:
        # Without http_path App Platform checks TCP. Django answers 400 to a
        # probe Host that is not in ALLOWED_HOSTS, so Django gets the TCP check.
        lines.append(f"      http_path: {health_path(config)}")
    lines.extend(["      initial_delay_seconds: 15", "      period_seconds: 30"])
    if not config.has_frontend:
        lines.extend(["    routes:", "      - path: /"])
    elif config.is_nextjs:
        # Same domain as the frontend; keep the prefix the backend mounts.
        lines.append("    routes:")
        for path in edge_backend_paths(config):
            lines.extend([f"      - path: {path}", "        preserve_path_prefix: true"])
    else:
        # Only the frontend proxy reaches the API, over the private network.
        lines.extend(["    internal_ports:", f"      - {port}"])
    lines.extend(_envs(config, web=True))
    return "\n".join(lines)


def _envs(config: ProjectConfig, *, web: bool) -> list[str]:
    """Return component envs for provider-wired values; operator values are app-level."""
    lines: list[str] = []
    for req in required_env(config):
        value = _value(config, req)
        if value is None or (req.web_only and not web):
            continue
        # Bindables stay GENERAL so App Platform interpolates them.
        lines.extend(
            [f"      - key: {req.name}", "        scope: RUN_TIME", f"        value: {value}"]
        )
    if web:
        for key, value in tls_env(config).items():
            lines.extend(
                [f"      - key: {key}", "        scope: RUN_TIME", f'        value: "{value}"']
            )
    return ["    envs:", *lines] if lines else []


def _value(config: ProjectConfig, req: EnvRequirement) -> str | None:
    """Return the bindable value for ``req``, or ``None`` for an operator value."""
    if req.name in _BINDABLE:
        return f"${{{_DB}.{_BINDABLE[req.name]}}}"
    if req.name == "DATABASE_URL" and config.is_nestjs_backend:
        # env.validation.ts accepts the postgresql:// scheme App Platform provides.
        return f"${{{_DB}.DATABASE_URL}}"
    if req.name == "ALLOWED_HOSTS":
        return "${APP_DOMAIN}"
    if req.name == "CORS_ORIGINS":
        # FastAPI parses list settings as JSON; quote so YAML keeps a string.
        return """'["${APP_URL}"]'"""
    if req.name == "WEBAUTHN_RP_ID":
        return "${APP_DOMAIN}"
    if req.name == "WEBAUTHN_ORIGIN":
        return "${APP_URL}"
    return None


def _frontend_service(config: ProjectConfig) -> str:
    lines = _component("frontend", FRONTEND_DOCKERFILE)
    port = FRONTEND_PORT if config.is_nextjs else 80
    lines.extend([f"    http_port: {port}", "    routes:", "      - path: /"])
    if config.has_backend and not config.is_nextjs:
        lines.extend(
            [
                "    envs:",
                "      - key: API_UPSTREAM",
                "        scope: RUN_TIME",
                f"        value: ${{{_API}.PRIVATE_URL}}",
                "      - key: API_PREFIX",
                "        scope: RUN_TIME",
                f"        value: {api_prefix(config)}",
            ]
        )
    return "\n".join(lines)


def _static() -> str:
    """Frontend-only static site; there is no API to call."""
    return "\n".join(
        [
            "  - name: frontend",
            "    github:",
            "      repo: OWNER/REPO",
            "      branch: main",
            "      deploy_on_push: true",
            "    source_dir: frontend",
            "    build_command: bun install --frozen-lockfile && bun run build",
            "    output_dir: dist",
            "    catchall_document: index.html",
            "    routes:",
            "      - path: /",
        ]
    )
