"""Railway Infrastructure as Code (``.railway/railway.ts``).

Railway deprecated Config as Code (``railway.json``/``railway.toml``): new
services cannot opt in and existing files stop being read on 2026-12-01
(https://docs.railway.com/config-as-code). The replacement is evaluated by
``railway config plan|apply`` (https://docs.railway.com/infrastructure-as-code).

The field names come from the published ``railway`` SDK (``railway/iac``
``IntentServiceConfig``, ``BuildConfig``, ``PostgresVariable``). Database
settings map to Railway's discrete ``PG*`` variables, so no URL is parsed.
Operator-supplied values use ``preserve()``: Railway keeps what
``railway variable set`` stored, and the image entrypoint reports any value
that is still missing.
"""

from __future__ import annotations

import json

from mattstack.config import ProjectConfig
from mattstack.runtime_profiles import task_processes
from mattstack.templates.deploy_runtime import (
    BACKEND_DOCKERFILE,
    ENTRYPOINT,
    MIGRATE_COMMAND,
    api_service,
    health_path,
    required_env,
    tls_env,
)

# Pinned to a release older than a week, so installs that enforce a minimum
# release age (bunfig minimumReleaseAge) resolve it. Requires CLI 5.42.1+.
RAILWAY_SDK_VERSION = "3.11.0"
MINIMUM_CLI_VERSION = "5.42.1"

_PG_REFS = {
    "DB_NAME": "PGDATABASE",
    "DB_USER": "PGUSER",
    # Provider variable name, not a credential value.
    "DB_PASSWORD": "PGPASSWORD",  # nosec B105
    "DB_HOST": "PGHOST",
    "DB_PORT": "PGPORT",
}
_REDIS_NAMES = ("REDIS_URL", "CELERY_BROKER_URL", "CELERY_RESULT_BACKEND")


def railway_files(config: ProjectConfig) -> dict[str, str]:
    return {
        ".railway/railway.ts": generate_railway_iac(config),
        ".railway/package.json": generate_railway_package_json(),
    }


def generate_railway_package_json() -> str:
    """Pin the SDK that ``railway config plan`` imports from ``railway/iac``."""
    data = {
        "private": True,
        "type": "module",
        "devDependencies": {"railway": RAILWAY_SDK_VERSION},
    }
    return json.dumps(data, indent=2) + "\n"


def generate_railway_iac(config: ProjectConfig) -> str:
    """Generate ``.railway/railway.ts`` for the backend, its database, and workers."""
    api = api_service(config)
    reqs = required_env(config)
    operator = [req.name for req in reqs if _ref(config, req.name) is None]
    shared = "\n".join(f"    {req.name}: {_ref(config, req.name) or 'preserve()'}," for req in reqs)
    for key, value in tls_env(config).items():
        shared += f"\n    {key}: {_ts(value)},"
    processes = task_processes(config, production=True)
    worker_env = ""
    if processes:
        entries = "\n".join(
            f"    {req.name}: {_ref(config, req.name) or f'api.env.{req.name}'},"
            for req in reqs
            if not req.web_only
        )
        worker_env = f"\n  const workerEnv = {{\n{entries}\n  }};\n"
    workers = "".join(
        f"""
  const {_ident(p.service)} = service({_ts(f"{config.name}-{p.service}")}, {{
    build: dockerfile,
    start: {_ts(f"{ENTRYPOINT} {p.command}")},
    env: workerEnv,
  }});
"""
        for p in processes
    )
    cache = '\n  const cache = redis("redis");' if config.use_redis else ""
    imports = "defineRailway, postgres, preserve, project, " + (
        "redis, service" if config.use_redis else "service"
    )
    resources = ["db", *(["cache"] if config.use_redis else []), "api"]
    resources.extend(_ident(p.service) for p in processes)
    secrets_lines = "\n".join(
        f"//   printf '%s' \"$VALUE\" | railway variable set --service {api} --skip-deploys "
        f"--stdin {name}"
        for name in operator
    )
    up_lines = "\n".join(
        f"//   railway up --service {config.name}-{p.service} --detach" for p in processes
    )
    return f"""\
// Generated by mattstack: Railway Infrastructure as Code for {config.display_name}.
// Docs: https://docs.railway.com/infrastructure-as-code
//
// Prerequisites:
//   railway --version            # needs {MINIMUM_CLI_VERSION}+; else run: railway upgrade --yes
//   bun install --cwd .railway   # installs the pinned railway SDK ({RAILWAY_SDK_VERSION})
//
// Deploy (authenticated; creates billable Railway resources):
//   railway login
//   railway link
//   railway config plan
//   railway config apply
// Set each operator value (preserve() keeps what you store):
{secrets_lines}
//   railway up --service {api} --detach
{up_lines}
//
// This file deploys the backend only; the frontend is not deployed by this target.
// The image entrypoint lists any missing value; reproduce locally with:
//   docker build -f {BACKEND_DOCKERFILE} -t {api}:check . && \\
//     docker run --rm --env-file .env.production {api}:check check
import {{ {imports} }} from "railway/iac";

export default defineRailway(() => {{
  const db = postgres("postgres");{cache}
  const dockerfile = {{
    builder: "DOCKERFILE" as const,
    dockerfilePath: {_ts(BACKEND_DOCKERFILE)},
  }};

  const api = service({_ts(api)}, {{
    build: dockerfile,
    preDeploy: {_ts(MIGRATE_COMMAND)},
    healthcheck: {_ts(health_path(config))},
    env: {{
{shared}
    }},
  }});
{worker_env}{workers}
  return project({_ts(config.name)}, {{
    resources: [{", ".join(resources)}],
  }});
}});
"""


def _ref(config: ProjectConfig, name: str) -> str | None:
    """Return the Railway reference for ``name``, or ``None`` for operator values."""
    if name in _PG_REFS:
        return f"db.env.{_PG_REFS[name]}"
    if name in _REDIS_NAMES and config.use_redis:
        return "cache.env.REDIS_URL"
    if name == "DATABASE_URL" and config.is_nestjs_backend:
        # env.validation.ts accepts postgresql://, the scheme Railway provides.
        return "db.env.DATABASE_URL"
    if name == "ALLOWED_HOSTS":
        # Railway healthchecks send Host: healthcheck.railway.app
        # (https://docs.railway.com/deployments/healthchecks). Add custom
        # domains to this list; IaC owns the value.
        return _ts("healthcheck.railway.app,${{RAILWAY_PUBLIC_DOMAIN}}")
    return None


def _ident(service: str) -> str:
    head, *rest = service.replace("_", "-").split("-")
    return head + "".join(part.title() for part in rest)


def _ts(value: str) -> str:
    return json.dumps(value)
