"""Fly.io app configuration (``fly.toml`` and, for full-stack, ``fly.frontend.toml``).

The backend app builds the generated production image and runs migrations as
the release command. ``fly postgres attach`` stores only ``DATABASE_URL``;
the Django settings read ``DB_*`` and nothing parses that URL, so the header
lists the ``fly secrets set`` commands for every required value. Task
workers run as Fly process groups from the same image.

A full-stack project deploys the frontend as a second app that reaches the
backend over Flycast (https://fly.io/docs/networking/flycast/): the backend
gets a private IPv6 address and no public IPs, binds 0.0.0.0, and does not
force HTTPS, because Flycast is HTTP-only.
"""

from __future__ import annotations

import json

from mattstack.config import ProjectConfig
from mattstack.runtime_profiles import task_processes
from mattstack.templates.deploy_runtime import (
    BACKEND_DOCKERFILE,
    ENTRYPOINT,
    FRONTEND_DOCKERFILE,
    MIGRATE_COMMAND,
    SERVE_COMMAND,
    health_path,
    required_env,
    tls_env,
    verify_command,
)
from mattstack.templates.frontend_runtime import FRONTEND_PORT, api_prefix

_REFERENCE = "# Reference: https://fly.io/docs/reference/configuration/"


def fly_files(config: ProjectConfig) -> dict[str, str]:
    """Return fly.toml, plus fly.frontend.toml for a full-stack project."""
    if not config.has_backend:
        return {"fly.toml": _frontend(config, config.name)}
    files = {"fly.toml": _backend(config)}
    if config.has_frontend:
        files["fly.frontend.toml"] = _frontend(config, f"{config.name}-frontend")
    return files


def flycast_origin(config: ProjectConfig) -> str:
    """Return the private backend origin other apps in the organization use."""
    return f"http://{config.name}.flycast"


def _backend(config: ProjectConfig) -> str:
    app = config.name
    processes = task_processes(config, production=True)
    secrets = "\n".join(
        f"#   fly secrets set {req.name}='<value>' --app {app}" for req in required_env(config)
    )
    process_lines = ""
    service_processes = ""
    if processes:
        # Fly's examples name groups app/worker; TaskProcess.role is unique per backend.
        groups = [f"  app = {json.dumps(SERVE_COMMAND)}"]
        groups.extend(f"  {p.role} = {json.dumps(f'{ENTRYPOINT} {p.command}')}" for p in processes)
        process_lines = "[processes]\n" + "\n".join(groups) + "\n\n"
        service_processes = '  processes = ["app"]\n'
    private = config.has_frontend
    access = (
        "# Private backend for fly.frontend.toml (live networking unverified without an account):\n"
        f"#   fly apps create {app} && fly ips allocate-v6 --private --app {app}\n"
        f"#   fly ips list --app {app}  # then: fly ips release <public-ip> --app {app}\n"
        f"# The frontend reaches it at {flycast_origin(config)}; include the frontend\n"
        f"# host ({app}-frontend.fly.dev) in ALLOWED_HOSTS for Django backends.\n"
        if private
        else ""
    )
    # Django answers 400 when the check's Host is not in ALLOWED_HOSTS.
    check_headers = (
        f"  # ALLOWED_HOSTS must include {app}.fly.dev for this check.\n"
        f'  headers = {{ Host = "{app}.fly.dev", X-Forwarded-Proto = "https" }}\n'
        if config.is_django_backend
        else ""
    )
    env_lines = "".join(f'  {key} = "{value}"\n' for key, value in tls_env(config).items())
    env_section = f"[env]\n{env_lines}\n" if env_lines else ""
    return f"""\
# Generated by mattstack.
{_REFERENCE}
# Validate: fly config validate --config fly.toml
# Required secrets (the image entrypoint lists any that are missing):
{secrets}
# Reproduce the startup check locally:
#   {verify_command(config)}
{access}app = "{app}"
primary_region = "iad"

[build]
  dockerfile = "{BACKEND_DOCKERFILE}"

[deploy]
  release_command = "{MIGRATE_COMMAND}"

{env_section}{process_lines}[http_service]
  internal_port = {config.backend_api_port}
  force_https = {"false" if private else "true"}
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
{service_processes}
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "{health_path(config)}"
  timeout = "5s"
{check_headers}

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
"""


def _frontend(config: ProjectConfig, app: str) -> str:
    port = FRONTEND_PORT if config.is_nextjs else 80
    upstream = ""
    deploy = f"#   fly deploy --config {'fly.frontend.toml' if config.has_backend else 'fly.toml'}"
    if config.has_backend and config.is_nextjs:
        # next.config.ts bakes the rewrite target into the build.
        upstream = f'\n[build.args]\n  INTERNAL_API_URL = "{flycast_origin(config)}"\n'
    elif config.has_backend:
        # nginx renders API_UPSTREAM into its template at startup.
        upstream = (
            f'\n[env]\n  API_UPSTREAM = "{flycast_origin(config)}"\n'
            f'  API_PREFIX = "{api_prefix(config)}"\n'
        )
    return f"""\
# Generated by mattstack.
{_REFERENCE}
# Validate: fly config validate --config {"fly.frontend.toml" if config.has_backend else "fly.toml"}
# Deploy:
{deploy}
app = "{app}"
primary_region = "iad"

[build]
  dockerfile = "{FRONTEND_DOCKERFILE}"
{upstream}
[http_service]
  internal_port = {port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/"
  timeout = "5s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
"""
