"""Root .env templates for generated projects.

The ports come first and the ``POSTGRES_*`` credentials come next, because
later keys refer to them with ``${NAME}``. ``make`` sources the file in a
shell, Compose interpolates it, and mattstack expands earlier keys, so each
credential has a single source on the host and in the containers.

Every secret named by ``env_secrets.secret_names`` is empty in the committed
examples. ``mattstack init`` fills the gitignored ``.env`` and
``.env.production`` with separate generated values.
"""

from __future__ import annotations

import json
from collections.abc import Callable

from mattstack.config import GraphStore, MediaStorage, ProjectConfig
from mattstack.runtime_profiles import (
    CENTRIFUGO_PORT,
    celery_env,
    task_backend_env,
)
from mattstack.templates.compose_env import pgvector_image
from mattstack.templates.frontend_runtime import (
    FRONTEND_PORT,
    PROD_API_SERVICE,
    browser_env,
    service_origin,
)
from mattstack.utils.env_secrets import generate_secrets

_DB = "${POSTGRES_DB}"
_USER = "${POSTGRES_USER}"
_PASSWORD = "${POSTGRES_PASSWORD}"  # nosec B105 # Environment reference, not a credential.
_Lookup = Callable[[str], str]
_REDIS_AUTH = ":${REDIS_PASSWORD}@"
_GENERATED_HEADER = (
    "# Generated by mattstack init for this environment only. Never commit this",
    "# file and never reuse these values in another environment.",
)


def generate_env_example(config: ProjectConfig, *, values: dict[str, str] | None = None) -> str:
    """Generate .env.example; ``values`` fills the secret names for .env."""
    secret = _secret_lookup(values)
    frontend_origin = "http://localhost:${FRONTEND_PORT}"
    lines: list[str] = [
        f"# Project: {config.display_name}",
        *(_GENERATED_HEADER if values else ()),
        "",
        "# === Ports (host side; Compose publishes these) ===",
        f"API_PORT={config.backend_api_port}",
        f"FRONTEND_PORT={FRONTEND_PORT}",
    ]
    if config.has_backend:
        lines.append("DB_PORT=5432")
        if config.use_redis:
            lines.append("REDIS_PORT=6379")
        if config.use_realtime:
            lines.append(f"CENTRIFUGO_PORT={CENTRIFUGO_PORT}")
    lines.append("")

    if config.has_backend:
        lines.extend(_database_lines(config, secret))
        db_url = f"{_USER}:{_PASSWORD}@localhost:${{DB_PORT}}/{_DB}"
        redis = f"redis://{_REDIS_AUTH}localhost:${{REDIS_PORT}}"
        if config.is_nestjs_backend:
            lines.extend(
                [
                    "# === Backend (NestJS) ===",
                    "NODE_ENV=development",
                    "PORT=${API_PORT}",
                    "HOST=0.0.0.0",
                    f'APP_NAME="{config.display_name}"',
                    "APP_URL=http://localhost:${API_PORT}",
                    f"DATABASE_URL=postgresql://{db_url}",
                    f"JWT_SECRET={secret('JWT_SECRET')}",
                    f"JWT_REFRESH_SECRET={secret('JWT_REFRESH_SECRET')}",
                    "JWT_ACCESS_EXPIRY=15m",
                    "JWT_REFRESH_EXPIRY=7d",
                    f"CORS_ORIGINS={frontend_origin}",
                ]
            )
            if config.use_redis:
                lines.append(f"REDIS_URL={redis}")
        else:
            label = "FastAPI" if config.is_fastapi_backend else "Django"
            scheme = "postgresql+asyncpg" if config.is_fastapi_backend else "postgres"
            lines.extend(
                [
                    f"# === Backend ({label}) ===",
                    "DEBUG=true",
                    f"SECRET_KEY={secret('SECRET_KEY')}",
                    f"DATABASE_URL={scheme}://{db_url}",
                ]
            )
            if config.is_django_backend:
                # DB_* is what the Django settings read; DATABASE_URL alone
                # leaves settings.DATABASES with an empty NAME.
                # DB_PORT is already set above: the host reaches the published port.
                lines.extend(_django_db_lines(host="localhost", port=None))
                if not config.is_django_matt:
                    lines.extend(["DJANGO_ENVIRONMENT=development", "ENVIRONMENT=development"])
                    lines.extend(_ninja_lines(config, secret))
                lines.extend(
                    [
                        "ALLOWED_HOSTS=localhost,127.0.0.1",
                        f"CORS_ALLOWED_ORIGINS={frontend_origin}",
                    ]
                )
            else:
                lines.extend(
                    [
                        "APP_ENV=development",
                        "APP_DEBUG=true",
                        f"JWT_SECRET_KEY={secret('JWT_SECRET_KEY')}",
                        _json_env("CORS_ORIGINS", [frontend_origin]),
                        _json_env("ALLOWED_HOSTS", ["localhost", "127.0.0.1"]),
                    ]
                )
            if config.use_redis:
                lines.append(f"REDIS_URL={redis}/0")
            lines.extend(f"{key}={value}" for key, value in celery_env(config, redis).items())
            lines.extend(_task_lines(config))
            if config.use_realtime:
                lines.extend(_realtime_lines(secret))
            lines.extend(_ai_lines(config, secret))
        lines.append("")

    if config.has_frontend:
        lines.extend(_frontend_lines(config, "http://localhost:${API_PORT}"))

    return "\n".join(lines).rstrip() + "\n"


def generate_env_file(config: ProjectConfig) -> str:
    """Generate the gitignored .env with fresh development secrets."""
    return generate_env_example(config, values=generate_secrets(config))


def generate_env_production_file(config: ProjectConfig) -> str:
    """Generate the gitignored .env.production with its own fresh secrets."""
    return generate_env_production_example(config, values=generate_secrets(config))


def _secret_lookup(values: dict[str, str] | None) -> _Lookup:
    found = values or {}
    return lambda name: found.get(name, "")


def _task_lines(config: ProjectConfig) -> list[str]:
    env = task_backend_env(config)
    if not env:
        return []
    comment = (
        "# TASK_BACKEND=none runs no worker: .delay() raises TaskDispatchDisabled"
        if env["TASK_BACKEND"] == "none"
        else "# Task backend; the worker runs under its Compose profile"
    )
    return [comment, f"TASK_BACKEND={env['TASK_BACKEND']}"]


def _ninja_lines(config: ProjectConfig, secret: _Lookup) -> list[str]:
    """api/settings/prod.py rejects a JWT key equal to SECRET_KEY."""
    return [
        f"NINJA_JWT_SIGNING_KEY={secret('NINJA_JWT_SIGNING_KEY')}",
        "# `python manage.py create_superuser` reads these; 12+ characters required",
        f"SUPERUSER_EMAIL=admin@{config.name}.localhost",
        "SUPERUSER_USERNAME=admin",
        f"SUPERUSER_PASSWORD={secret('SUPERUSER_PASSWORD')}",
        "SUPERUSER_FIRST_NAME=Admin",
        "SUPERUSER_LAST_NAME=User",
    ]


def _realtime_lines(secret: _Lookup) -> list[str]:
    """Centrifugo keys; Compose maps them onto the Centrifugo container too."""
    names = (
        "CENTRIFUGO_API_KEY",
        "CENTRIFUGO_TOKEN_SECRET",
        "CENTRIFUGO_ADMIN_PASSWORD",
        "CENTRIFUGO_ADMIN_SECRET",
    )
    return [
        "",
        "# === Realtime (Centrifugo; start with: make up-realtime) ===",
        "CENTRIFUGO_URL=http://localhost:${CENTRIFUGO_PORT}",
        *(f"{name}={secret(name)}" for name in names),
    ]


def _ai_lines(config: ProjectConfig, secret: _Lookup) -> list[str]:
    """AI layer (backend docs/AI_LAYER.md): the ``ai`` extra and the pgvector image."""
    if not config.use_ai:
        return []
    lines = [
        "",
        f"# === AI layer (vector store: {config.ai_store.value}, graph: "
        f"{config.graph_store.value}) ===",
        "AI_ENABLED=true",
        f"POSTGRES_IMAGE={pgvector_image(config)}",
        "# Optional extras baked into the backend image",
        "UV_EXTRAS=ai",
    ]
    if config.graph_store == GraphStore.NEO4J:
        lines.append(f"NEO4J_PASSWORD={secret('NEO4J_PASSWORD')}")
    return lines


def generate_env_production_example(
    config: ProjectConfig, *, values: dict[str, str] | None = None
) -> str:
    """Generate .env.production.example; Compose fails if a secret is missing."""
    secret = _secret_lookup(values)
    origin = "https://your-domain.com"
    lines: list[str] = [
        f"# Project: {config.display_name} (production)",
        *(_GENERATED_HEADER if values else ()),
        "# Used with: docker compose -f docker-compose.prod.yml --env-file .env.production",
        "",
        "# === Ports (host side) ===",
        f"API_PORT={config.backend_api_port}",
        "FRONTEND_PORT=80",
    ]
    if config.use_realtime:
        lines.append(f"CENTRIFUGO_PORT={CENTRIFUGO_PORT}")
    lines.append("")

    if config.has_backend:
        lines.extend(_database_lines(config, secret))
        db_url = f"{_USER}:{_PASSWORD}@db:5432/{_DB}"
        redis = f"redis://{_REDIS_AUTH}redis:6379"
        if config.is_nestjs_backend:
            lines.extend(
                [
                    "# === Backend (NestJS) ===",
                    "NODE_ENV=production",
                    f"PORT={config.backend_api_port}",
                    f'APP_NAME="{config.display_name}"',
                    f"APP_URL={origin}",
                    f"DATABASE_URL=postgresql://{db_url}",
                    f"JWT_SECRET={secret('JWT_SECRET')}",
                    f"JWT_REFRESH_SECRET={secret('JWT_REFRESH_SECRET')}",
                    f"CORS_ORIGINS={origin}",
                ]
            )
            if config.use_redis:
                lines.append(f"REDIS_URL={redis}")
        else:
            label = "FastAPI" if config.is_fastapi_backend else "Django"
            scheme = "postgresql+asyncpg" if config.is_fastapi_backend else "postgres"
            lines.extend(
                [
                    f"# === Backend ({label}) ===",
                    "DEBUG=false",
                    f"SECRET_KEY={secret('SECRET_KEY')}",
                    f"DATABASE_URL={scheme}://{db_url}",
                ]
            )
            if config.is_django_backend:
                lines.append("DJANGO_ENVIRONMENT=production")
                if not config.is_django_matt:
                    lines.extend(["ENVIRONMENT=production", *_ninja_lines(config, secret)])
                lines.extend(_django_db_lines(host="db", port="5432"))
                lines.extend(
                    [
                        f"ALLOWED_HOSTS={origin.removeprefix('https://')}",
                        f"CORS_ALLOWED_ORIGINS={origin}",
                        f"CSRF_TRUSTED_ORIGINS={origin}",
                    ]
                )
            else:
                lines.extend(
                    [
                        "APP_ENV=production",
                        "APP_DEBUG=false",
                        f"JWT_SECRET_KEY={secret('JWT_SECRET_KEY')}",
                        _json_env("CORS_ORIGINS", [origin]),
                        _json_env("ALLOWED_HOSTS", [origin.removeprefix("https://")]),
                        f"WEBAUTHN_RP_ID={origin.removeprefix('https://')}",
                        f"WEBAUTHN_ORIGIN={origin}",
                    ]
                )
            if config.use_redis:
                lines.append(f"REDIS_URL={redis}/0")
            lines.extend(f"{key}={value}" for key, value in celery_env(config, redis).items())
            lines.extend(_task_lines(config))
            if config.use_realtime:
                lines.extend(
                    [
                        "",
                        "# === Realtime (Centrifugo) ===",
                        f"CENTRIFUGO_API_KEY={secret('CENTRIFUGO_API_KEY')}",
                        f"CENTRIFUGO_TOKEN_SECRET={secret('CENTRIFUGO_TOKEN_SECRET')}",
                        f"CENTRIFUGO_ADMIN_PASSWORD={secret('CENTRIFUGO_ADMIN_PASSWORD')}",
                        f"CENTRIFUGO_ADMIN_SECRET={secret('CENTRIFUGO_ADMIN_SECRET')}",
                        "# Browser origins allowed to open a WebSocket, space separated",
                        f"CENTRIFUGO_ALLOWED_ORIGINS={origin}",
                    ]
                )
            lines.extend(_ai_lines(config, secret))
            if config.media_storage == MediaStorage.S3:
                lines.extend(
                    [
                        "",
                        "# === Media storage (S3, opt-in; static files stay local) ===",
                        "AWS_STORAGE_BUCKET_NAME=",
                        "AWS_ACCESS_KEY_ID=",
                        "AWS_SECRET_ACCESS_KEY=",
                        "AWS_S3_REGION_NAME=us-east-1",
                    ]
                )
        lines.append("")

    if config.has_frontend:
        lines.extend(_frontend_lines(config, service_origin(config, PROD_API_SERVICE)))

    return "\n".join(lines).rstrip() + "\n"


def _database_lines(config: ProjectConfig, secret: _Lookup) -> list[str]:
    """``DB_PASSWORD`` is the secret (the Ninja script generates that name)."""
    lines = [
        "# === Database (single source; other keys refer to these) ===",
        f"DB_PASSWORD={secret('DB_PASSWORD')}",
        f"POSTGRES_DB={config.python_package_name}",
        "POSTGRES_USER=postgres",
        "POSTGRES_PASSWORD=${DB_PASSWORD}",
    ]
    if config.use_redis:
        lines.append(f"REDIS_PASSWORD={secret('REDIS_PASSWORD')}")
    return [*lines, ""]


def _django_db_lines(*, host: str, port: str | None) -> list[str]:
    lines = [
        f"DB_NAME={_DB}",
        f"DB_USER={_USER}",
        f"DB_HOST={host}",
    ]
    return [*lines, f"DB_PORT={port}"] if port else lines


def _frontend_lines(config: ProjectConfig, backend_origin: str) -> list[str]:
    """The browser calls a relative prefix; the dev server or nginx proxies it.

    `make frontend-dev` and `make frontend-build` load these, so a fresh clone,
    which has no gitignored frontend/.env, still builds with the right values.
    """
    label = "Next.js" if config.is_nextjs else "Frontend"
    lines = [f"# === {label} ==="]
    if config.has_backend:
        lines.extend(f"{key}={value}" for key, value in browser_env(config).items())
        if config.is_nextjs:
            lines.append(f"INTERNAL_API_URL={backend_origin}")
    return [*lines, ""] if len(lines) > 1 else []


def _json_env(key: str, values: list[str]) -> str:
    """Quote JSON list settings so dotenv, Compose, and shell exports preserve them."""
    return f"{key}={json.dumps(json.dumps(values))}"
